// infoq-scaffold-frontend-weapp-react/src/pages/system-depts/index.tsx
import {View} from '@tarojs/components';
import Taro, {useDidShow} from '@tarojs/taro';
import {
  assertArrayData,
  delDept,
  type DeptQuery,
  type DeptVO,
  type DictOption,
  flattenTree,
  type FlatTreeItem,
  getDictLabel,
  getDicts,
  listDept,
  toDictOptions
} from '@/api';
import {useState} from 'react';
import {AtButton, AtInput} from 'taro-ui';
import BottomNav from '../../components/bottom-nav';
import {EmptyNotice, FabButton, KeyValueList, RecordCard, StatusTag} from '../../components/taro-ui-kit';
import {navigate, routes} from '../../utils/navigation';
import {handlePageError, showSuccess} from '../../utils/ui';
import {useSessionStore} from '../../store/session';
import './index.scss';

const createQuery = (): DeptQuery => ({
  pageNum: 1,
  pageSize: 100,
  deptName: '',
  deptCategory: '',
  status: ''
});

export default function SystemDeptsPage() {
  const permissions = useSessionStore((state) => state.permissions);
  const loadSession = useSessionStore((state) => state.loadSession);
  const [query, setQuery] = useState<DeptQuery>(createQuery());
  const [list, setList] = useState<Array<FlatTreeItem<DeptVO>>>([]);
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);

  const canList = permissions.includes('system:dept:list');
  const canAdd = permissions.includes('system:dept:add');
  const canEdit = permissions.includes('system:dept:edit');
  const canRemove = permissions.includes('system:dept:remove');

  const loadPage = async (nextQuery = query) => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }
      const [statusResponse, listResponse] = await Promise.all([
        getDicts('sys_normal_disable'),
        canList ? listDept(nextQuery) : Promise.resolve({ data: [] as DeptVO[] })
      ]);
      setStatusOptions(toDictOptions(statusResponse.data));
      setList(flattenTree(assertArrayData(listResponse.data, '部门列表响应 data')));
    } catch (error) {
      await handlePageError(error, '部门列表加载失败');
    }
  };

  useDidShow(() => {
    void loadPage();
  });

  const openCreate = (parentId?: string | number) => {
    navigate(`${routes.deptForm}${parentId !== undefined ? `?parentId=${parentId}` : ''}`);
  };

  const openEdit = (deptId: string | number) => {
    navigate(`${routes.deptForm}?deptId=${deptId}`);
  };

  const handleDelete = async (deptId: string | number) => {
    const modal = await Taro.showModal({
      title: '确认删除',
      content: `确定删除部门 #${deptId} 吗？`
    });
    if (!modal.confirm) return;
    try {
      await delDept(deptId);
      await showSuccess('部门已删除');
      await loadPage({ ...query });
    } catch (error) {
      await handlePageError(error, '部门删除失败');
    }
  };

  return (
    <View className="list-container">
      <View className="search-section">
        <View className="search-card">
          <AtInput
            clear
            name="deptName"
            placeholder="按部门名称过滤"
            title="部门名称"
            value={query.deptName || ''}
            onChange={(value) => {
              setQuery((prev) => ({ ...prev, deptName: String(value) }));
              return value;
            }}
          />
          <View className="search-actions">
            <AtButton
              className="search-action-btn"
              type="secondary"
              onClick={() => {
                const nextQuery = createQuery();
                setQuery(nextQuery);
                void loadPage(nextQuery);
              }}
            >
              重置
            </AtButton>
            <AtButton
              className="search-action-btn"
              type="primary"
              onClick={() => void loadPage({ ...query })}
            >
              查询
            </AtButton>
          </View>
        </View>
      </View>

      <View className="list-content">
        {!canList && <EmptyNotice message="当前账号没有访问权限" />}
        {canList && list.length === 0 && <EmptyNotice message="未查询到相关部门" />}
        {canList && list.map((item) => (
          <RecordCard
            key={String(item.deptId)}
            icon="folder"
            title={`${'· '.repeat(item._depth)}${item.deptName}`}
            statusColor={item.status === '0' ? '#52c41a' : '#ff4d4f'}
            extra={
              <StatusTag
                label={getDictLabel(statusOptions, item.status) || '未知'}
                type={item.status === '0' ? 'success' : 'error'}
              />
            }
            actions={[
              ...(canAdd ? [{ onClick: () => openCreate(item.deptId), title: '新增下级' }] : []),
              ...(canEdit ? [{ onClick: () => void openEdit(item.deptId), title: '编辑' }] : []),
              ...(canRemove ? [{
                onClick: () => void handleDelete(item.deptId),
                title: '删除',
                danger: true
              }] : [])
            ]}
          >
            <KeyValueList
              items={[
                { label: '上级部门', value: item.parentName || '顶级部门' },
                { label: '部门类别', value: item.deptCategory || '-' },
                { label: '联系方式', value: item.phone || item.email || '-' }
              ]}
            />
          </RecordCard>
        ))}
      </View>

      {canAdd && <FabButton onClick={() => openCreate()} />}

      <BottomNav active="admin" />
    </View>
  );
}

// infoq-scaffold-frontend-weapp-vue/src/pages/system-depts/index.vue
<template>
  <view class="list-container">
    <view class="search-section">
      <view class="search-card">
        <view class="search-field">
          <text class="field-label">部门名称</text>
          <view class="field-input-box">
            <input v-model="query.deptName" placeholder="按部门名称过滤" placeholder-style="color: #94a3b8" />
          </view>
        </view>
        <view class="search-actions">
  <button class="secondary-btn search-action-btn" @click="handleReset">重置</button>
  <button class="primary-btn search-action-btn" @click="handleSearch">查询</button>
</view>
      </view>
    </view>

    <view class="list-content">
      <EmptyNotice v-if="!canList" message="暂无访问权限" />
      <EmptyNotice v-else-if="filteredRows.length === 0" message="未查询到相关部门" />

      <template v-if="canList">
        <RecordCard
          v-for="item in filteredRows"
          :key="String(item.deptId)"
          icon="folder"
          :title="item.deptName"
          :actions="getActions(item)"
        >
          <template #extra>
            <StatusTag
              :label="item.status === '0' ? '正常' : '停用'"
              :type="item.status === '0' ? 'success' : 'error'"
            />
          </template>

          <KeyValueList
            :items="[
              { label: '负责人', value: item.leader || '-' },
              { label: '联系电话', value: item.phone || '-' },
              { label: '创建时间', value: item.createTime ? String(item.createTime).split(' ')[0] : '-' }
            ]"
          />
        </RecordCard>
      </template>
    </view>

    <FabButton v-if="canAdd" @click="openCreate" />

    <BottomNav active="admin" />
  </view>
</template>

<script setup lang="ts">
import {computed, reactive, ref} from 'vue';
import {onShow} from '@dcloudio/uni-app';
import {assertArrayData, delDept, type DeptVO, listDept} from '@/api';
import {ensureAuthenticated} from '@/composables/use-auth-guard';
import {navigate, routes} from '@/utils/navigation';
import {handlePageError, showSuccess} from '@/utils/ui';
import {useSessionStore} from '@/store/session';

import BottomNav from '@/components/BottomNav.vue';
import EmptyNotice from '@/components/EmptyNotice.vue';
import KeyValueList from '@/components/KeyValueList.vue';
import RecordCard from '@/components/RecordCard.vue';
import StatusTag from '@/components/StatusTag.vue';
import FabButton from '@/components/FabButton.vue';

const sessionStore = useSessionStore();
const rows = ref<DeptVO[]>([]);
const query = reactive({
  deptName: '',
  status: ''
});

const canList = computed(() => sessionStore.permissions.includes('system:dept:list'));
const canAdd = computed(() => sessionStore.permissions.includes('system:dept:add'));
const canEdit = computed(() => sessionStore.permissions.includes('system:dept:edit'));
const canRemove = computed(() => sessionStore.permissions.includes('system:dept:remove'));

const filteredRows = computed(() => {
  if (!query.deptName) return rows.value;
  const filter = query.deptName.toLowerCase();
  return rows.value.filter(r => r.deptName.toLowerCase().includes(filter));
});

const loadData = async () => {
  if (!ensureAuthenticated()) return;
  try {
    await sessionStore.loadSession();
    const response = await listDept();
    rows.value = assertArrayData(response.data, '部门列表响应 data');
  } catch (error) {
    await handlePageError(error, '部门加载失败');
  }
};

const handleSearch = () => {
  void loadData();
};

const handleReset = () => {
  query.deptName = '';
  void loadData();
};

const openCreate = () => navigate(routes.deptForm);

const getActions = (item: DeptVO) => {
  const actions = [];
  if (canEdit.value) {
    actions.push({ title: '编辑', onClick: () => navigate(`${routes.deptForm}?deptId=${item.deptId}`) });
  }
  if (canRemove.value) {
    actions.push({ title: '删除', danger: true, onClick: () => removeItem(item.deptId) });
  }
  return actions;
};

const removeItem = async (deptId: string | number) => {
  const res = await uni.showModal({ title: '确认删除', content: '确定删除该部门吗？' });
  if (!res.confirm) return;
  try {
    await delDept(deptId);
    await showSuccess('删除成功');
    await loadData();
  } catch (error) {
    await handlePageError(error, '删除失败');
  }
};

onShow(() => {
  void loadData();
});
</script>

<style lang="scss">
@import './index.scss';
</style>
