// infoq-scaffold-frontend-weapp-vue/src/pages/profile-edit/index.vue
<template>
  <view class="profile-edit-container">
    <view class="edit-header-banner">
      <view class="banner-title">完善个人资料</view>
      <view class="avatar-edit-box" @click="handleUpdateAvatar">
        <view class="avatar-frame">
          <image :src="avatarImage" class="avatar-img" mode="aspectFill" @error="handleAvatarLoadError" />
        </view>
        <view class="edit-badge">
          <AppIcon name="camera" size="32" color="#1677ff" />
        </view>
      </view>
    </view>

    <view class="form-wrapper">
      <view class="form-card-modern">
        <view class="modern-form-item">
          <view class="label-row">
            <view class="dot"></view>
            <text class="text">用户昵称</text>
          </view>
          <input class="modern-input" v-model="form.nickName" placeholder="起一个好听的名字" />
        </view>

        <view class="modern-form-item">
          <view class="label-row">
            <view class="dot"></view>
            <text class="text">性别设置</text>
          </view>
          <view class="sex-selector">
            <view
              class="sex-btn"
              :class="{ active: form.sex === '0' }"
              @click="form.sex = '0'"
            >男</view>
            <view
              class="sex-btn"
              :class="{ active: form.sex === '1' }"
              @click="form.sex = '1'"
            >女</view>
            <view
              class="sex-btn"
              :class="{ active: form.sex === '2' }"
              @click="form.sex = '2'"
            >保密</view>
          </view>
        </view>

        <view class="modern-form-item">
          <view class="label-row">
            <view class="dot"></view>
            <text class="text">联系电话</text>
          </view>
          <input class="modern-input" v-model="form.phonenumber" placeholder="方便大家联系你" type="number" />
        </view>

        <view class="modern-form-item">
          <view class="label-row">
            <view class="dot"></view>
            <text class="text">电子邮箱</text>
          </view>
          <input class="modern-input" v-model="form.email" placeholder="接收系统通知" />
        </view>

        <view class="btn-group-modern">
          <view class="modern-btn primary" @click="handleSave">确认保存</view>
          <view class="modern-btn secondary" @click="backOr(routes.profile)">放弃修改</view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup lang="ts">
import {computed, reactive, ref, watch} from 'vue';
import {onShow} from '@dcloudio/uni-app';
import {assertObjectData, getUserProfile, updateUserProfile} from '@/api';
import defaultAvatar from '@/assets/images/profile.jpg';
import {ensureAuthenticated} from '@/composables/use-auth-guard';
import {backOr, routes} from '@/utils/navigation';
import {resolveAvatarUrl} from '@/utils/avatar';
import {handlePageError, showSuccess} from '@/utils/ui';
import {useSessionStore} from '@/store/session';

const sessionStore = useSessionStore();
const form = reactive({
  nickName: '',
  email: '',
  phonenumber: '',
  sex: '0',
  avatar: ''
});
const avatarLoadFailed = ref(false);
watch(
  () => form.avatar,
  () => {
    avatarLoadFailed.value = false;
  }
);

const avatarImage = computed(() => {
  if (avatarLoadFailed.value) {
    return defaultAvatar;
  }
  return resolveAvatarUrl(form.avatar) || defaultAvatar;
});

const handleAvatarLoadError = () => {
  avatarLoadFailed.value = true;
};

const loadProfile = async () => {
  if (!ensureAuthenticated()) {
    return;
  }
  try {
    await sessionStore.loadSession();
    const response = await getUserProfile();
    const user = assertObjectData(response.data.user, '用户资料响应 data.user');
    form.nickName = user.nickName || '';
    form.email = user.email || '';
    form.phonenumber = user.phonenumber || '';
    form.sex = user.sex || '0';
    form.avatar = user.avatar || '';
  } catch (error) {
    await handlePageError(error, '资料加载失败');
  }
};

const handleUpdateAvatar = () => {
  uni.showToast({ title: '移动端头像上传暂未开放', icon: 'none' });
};

const handleSave = async () => {
  if (!form.nickName.trim()) {
    await uni.showToast({ title: '请输入昵称', icon: 'none' });
    return;
  }
  try {
    await updateUserProfile(form);
    await showSuccess('更新成功');
    backOr(routes.profile);
  } catch (error) {
    await handlePageError(error, '更新失败');
  }
};

onShow(() => {
  void loadProfile();
});
</script>

<style lang="scss">
@import './index.scss';
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/profile-edit/index.tsx
import {Text, View} from '@tarojs/components';
import Taro, {useDidShow} from '@tarojs/taro';
import {AtAvatar, AtButton, AtIcon, AtInput} from 'taro-ui';
import {
  assertAvatarUploadData,
  type DictOption,
  getDicts,
  getUserProfile,
  toDictOptions,
  updateUserProfile,
  uploadAvatar,
  type UserForm,
  type UserProfileUpdatePayload
} from '@/api';
import defaultAvatar from '@/assets/images/profile.jpg';
import {useState} from 'react';
import {useSessionStore} from '../../store/session';
import {resolveAvatarUrl} from '../../utils/avatar';
import {backOr, routes} from '../../utils/navigation';
import {handlePageError, showSuccess} from '../../utils/ui';
import './index.scss';

type ProfileFormState = UserForm & { avatar?: string };

const getDisplayName = (userName?: string, nickName?: string) => (nickName || userName || '移动端用户').slice(0, 1).toUpperCase();

export default function ProfileEditPage() {
  const loadSession = useSessionStore((state) => state.loadSession);
  const patchUser = useSessionStore((state) => state.patchUser);
  const [sexOptions, setSexOptions] = useState<DictOption[]>([]);
  const [form, setForm] = useState<ProfileFormState>({
    userName: '',
    nickName: '',
    phonenumber: '',
    email: '',
    sex: '',
    avatar: ''
  });
  const avatarImage = resolveAvatarUrl(form.avatar) || defaultAvatar;

  useDidShow(() => {
    const run = async () => {
      try {
        const session = await loadSession(true);
        if (!session) {
          Taro.reLaunch({ url: routes.login });
          return;
        }
        const [profileResponse, sexResponse] = await Promise.all([getUserProfile(), getDicts('sys_user_sex')]);
        setSexOptions(toDictOptions(sexResponse.data));
        setForm({
          ...profileResponse.data.user,
          password: '',
          postIds: [],
          roleIds: []
        } as ProfileFormState);
      } catch (error) {
        await handlePageError(error, '基本资料加载失败。');
      }
    };
    void run();
  });

  const handleSave = async () => {
    if (!form.nickName?.trim()) {
      await Taro.showToast({ title: '请输入用户昵称。', icon: 'none' });
      return;
    }
    if (!form.phonenumber?.trim()) {
      await Taro.showToast({ title: '请输入手机号。', icon: 'none' });
      return;
    }
    if (!/^1[3456789][0-9]\d{8}$/.test(form.phonenumber)) {
      await Taro.showToast({ title: '请输入正确的手机号。', icon: 'none' });
      return;
    }
    if (form.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) {
      await Taro.showToast({ title: '请输入正确的邮箱地址。', icon: 'none' });
      return;
    }
    const payload: UserProfileUpdatePayload = {
      nickName: form.nickName?.trim(),
      phonenumber: form.phonenumber?.trim(),
      email: form.email?.trim(),
      sex: form.sex
    };
    try {
      await updateUserProfile(payload);
      patchUser({
        avatar: form.avatar,
        email: payload.email,
        nickName: payload.nickName,
        phonenumber: payload.phonenumber,
        sex: payload.sex
      });
      await showSuccess('资料已更新');
      backOr(routes.profile);
    } catch (error) {
      await handlePageError(error, '资料更新失败。');
    }
  };

  const handleChooseAvatar = async () => {
    try {
      const result = await Taro.chooseImage({
        count: 1,
        sizeType: ['compressed'],
        sourceType: ['album', 'camera']
      });
      const filePath = result.tempFilePaths?.[0];
      if (!filePath) {
        return;
      }
      const response = await uploadAvatar(filePath);
      const { imgUrl } = assertAvatarUploadData(response.data);
      setForm((prev) => ({ ...prev, avatar: imgUrl }));
      patchUser({ avatar: imgUrl });
      await showSuccess('头像已更新');
    } catch (error) {
      await handlePageError(error, '头像上传失败。');
    }
  };

  return (
    <View className="profile-edit-container">
      <View className="avatar-section">
        <View className="avatar-wrapper" onClick={() => void handleChooseAvatar()}>
          <AtAvatar
            circle
            image={avatarImage}
            text={getDisplayName(form.userName, form.nickName)}
          />
          <View className="camera-icon">
            <AtIcon value="camera" size="14" color="#fff" />
          </View>
        </View>
        <View className="account-text">
          当前账号: <Text className="account-value">{form.userName || '未命名用户'}</Text>
        </View>
      </View>

      <View className="form-section">
        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">基本信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            <AtInput
              clear
              name="nickName"
              placeholder="请输入用户昵称"
              title="用户昵称"
              value={form.nickName || ''}
              onChange={(value) => {
                setForm((prev) => ({ ...prev, nickName: String(value) }));
                return value;
              }}
            />
            <AtInput
              clear
              name="phonenumber"
              placeholder="请输入手机号"
              title="手机号"
              type="phone"
              value={form.phonenumber || ''}
              onChange={(value) => {
                setForm((prev) => ({ ...prev, phonenumber: String(value) }));
                return value;
              }}
            />
            <AtInput
              clear
              name="email"
              placeholder="请输入邮箱地址"
              title="邮箱"
              value={form.email || ''}
              onChange={(value) => {
                setForm((prev) => ({ ...prev, email: String(value) }));
                return value;
              }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">性别</Text>
          </View>
          <View className="card-content">
            <View className="sex-options-horizontal">
              {sexOptions.map((item) => (
                <View
                  key={item.value}
                  className={`sex-option-item ${form.sex === item.value ? 'active' : ''}`}
                  onClick={() => setForm((prev) => ({ ...prev, sex: item.value }))}
                >
                  <View className="radio-circle">
                    {form.sex === item.value && <View className="radio-inner" />}
                  </View>
                  <Text className="sex-label">{item.label}</Text>
                </View>
              ))}
            </View>
          </View>
        </View>
      </View>

      <View className="action-section">
        <AtButton className="save-btn" type="primary" onClick={() => void handleSave()}>
          保存资料
        </AtButton>
        <AtButton className="cancel-btn" onClick={() => backOr(routes.profile)}>
          返回
        </AtButton>
      </View>
    </View>
  );
}
