// infoq-scaffold-frontend-react/src/pages/register.tsx
import { App, Button, Form, Input } from 'antd';
import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { checkInviteCode, getCodeImg, register as registerApi, sendEmailCode } from '@/api/login';
import type { RegisterForm } from '@/api/types';
import AuthPageShell from '@/components/AuthPageShell';
import SvgIcon from '@/components/SvgIcon';
import { useTranslation } from 'react-i18next';

const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

export default function RegisterPage() {
  const [form] = Form.useForm<RegisterForm>();
  const [loading, setLoading] = useState(false);
  const [sendingCode, setSendingCode] = useState(false);
  const [countdown, setCountdown] = useState(0);
  const [captchaEnabled, setCaptchaEnabled] = useState(true);
  const [codeUrl, setCodeUrl] = useState('');
  const [inviteRegisterEnabled, setInviteRegisterEnabled] = useState(false);
  const [inviteCodeValid, setInviteCodeValid] = useState(false);
  const [inviteChecking, setInviteChecking] = useState(false);
  const [lastValidatedInviteCode, setLastValidatedInviteCode] = useState('');
  const navigate = useNavigate();
  const { t } = useTranslation();
  const { message } = App.useApp();
  const title = import.meta.env.VITE_APP_TITLE || t('login.title');
  const authIconStyle = { color: '#bfbfbf' };

  const getCode = useCallback(async () => {
    try {
      const res = await getCodeImg();
      const data = res?.data;
      if (!data?.registerEnabled || !data.mailEnabled) {
        navigate('/login', { replace: true });
        return;
      }
      const inviteEnabled = data.inviteRegisterEnabled === true;
      setInviteRegisterEnabled(inviteEnabled);
      if (!inviteEnabled) {
        setInviteCodeValid(false);
        setLastValidatedInviteCode('');
        form.setFieldValue('inviteCode', undefined);
      }
      const enabled = data.captchaEnabled === undefined ? true : data.captchaEnabled;
      setCaptchaEnabled(enabled);
      if (enabled) {
        setCodeUrl(`data:image/gif;base64,${data.img || ''}`);
        form.setFieldValue('uuid', data.uuid);
        form.setFieldValue('code', '');
        return;
      }
      setCodeUrl('');
      form.setFieldValue('uuid', undefined);
      form.setFieldValue('code', undefined);
    } catch {
      setCodeUrl('');
      form.setFieldValue('code', '');
      form.setFieldValue('uuid', undefined);
    }
  }, [form, navigate]);

  useEffect(() => {
    if (countdown <= 0) {
      return undefined;
    }
    const timerId = window.setTimeout(() => {
      setCountdown((value) => value - 1);
    }, 1000);
    return () => {
      window.clearTimeout(timerId);
    };
  }, [countdown]);

  useEffect(() => {
    document.title = title;
    form.setFieldsValue({
      email: '',
      emailCode: '',
      inviteCode: '',
      username: '',
      password: '',
      confirmPassword: '',
      code: '',
      uuid: ''
    });
    getCode();
  }, [form, getCode, title]);

  const countdownText =
    countdown > 0 ? t('register.countdown', { seconds: countdown }) : sendingCode ? t('register.sendingCode') : t('register.sendCode');

  const handleInviteBlur = async () => {
    if (!inviteRegisterEnabled) {
      return;
    }
    const inviteCode = form.getFieldValue('inviteCode')?.trim();
    form.setFieldValue('inviteCode', inviteCode);
    if (!inviteCode) {
      setInviteCodeValid(false);
      setLastValidatedInviteCode('');
      return;
    }
    if (inviteCodeValid && lastValidatedInviteCode === inviteCode) {
      return;
    }
    setInviteChecking(true);
    try {
      await checkInviteCode(inviteCode);
      setInviteCodeValid(true);
      setLastValidatedInviteCode(inviteCode);
    } catch {
      setInviteCodeValid(false);
      setLastValidatedInviteCode('');
      await form.validateFields(['inviteCode']).catch(() => undefined);
    } finally {
      setInviteChecking(false);
    }
  };

  const handleInviteChange = () => {
    if (!inviteRegisterEnabled) {
      return;
    }
    setInviteCodeValid(false);
    setLastValidatedInviteCode('');
  };

  const handleSendCode = async () => {
    try {
      const fields = inviteRegisterEnabled ? ['inviteCode', 'email'] : ['email'];
      if (captchaEnabled) {
        fields.push('code');
      }
      await form.validateFields(fields);
    } catch {
      return;
    }

    if (inviteRegisterEnabled && !inviteCodeValid) {
      return;
    }

    const values = form.getFieldsValue(['inviteCode', 'email', 'code', 'uuid']);
    setSendingCode(true);
    try {
      await sendEmailCode({
        inviteCode: values.inviteCode,
        email: values.email,
        scene: 'register',
        code: values.code,
        uuid: values.uuid
      });
      message.success(t('register.codeSent'));
      form.setFieldValue('code', '');
      setCountdown(60);
    } finally {
      setSendingCode(false);
      if (captchaEnabled) {
        await getCode();
      }
    }
  };

  const onFinish = async (values: RegisterForm) => {
    if (inviteRegisterEnabled && !inviteCodeValid) {
      await form.validateFields(['inviteCode']).catch(() => undefined);
      return;
    }
    setLoading(true);
    try {
      await registerApi(values);
      message.success(t('register.registerSuccess', { username: values.username }));
      navigate('/login');
    } catch {
      if (captchaEnabled) {
        await getCode();
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthPageShell title={title}>
      <Form form={form} onFinish={onFinish}>
        <Form.Item name="uuid" hidden>
          <Input />
        </Form.Item>

        {inviteRegisterEnabled && (
          <Form.Item
            name="inviteCode"
            style={{ marginBottom: 22 }}
            rules={[
              { required: true, message: t('register.rule.inviteCode.required') },
              {
                validator: async (_, value) => {
                  if (!inviteRegisterEnabled) {
                    return;
                  }
                  if (!value) {
                    throw new Error(t('register.rule.inviteCode.required'));
                  }
                  if (!inviteCodeValid) {
                    throw new Error(t('register.rule.inviteCode.invalid'));
                  }
                }
              }
            ]}
          >
            <Input
              size="large"
              autoComplete="off"
              placeholder={t('register.inviteCode')}
              prefix={<SvgIcon iconClass="password" size={14} style={authIconStyle} />}
              onBlur={handleInviteBlur}
              onChange={handleInviteChange}
            />
          </Form.Item>
        )}

        <Form.Item
          name="email"
          style={{ marginBottom: 22 }}
          rules={[
            { required: true, message: t('register.rule.email.required') },
            { type: 'email', message: t('register.rule.email.invalid') }
          ]}
        >
          <Input
            size="large"
            autoComplete="email"
            placeholder={t('register.email')}
            prefix={<SvgIcon iconClass="email" size={14} style={authIconStyle} />}
          />
        </Form.Item>

        <div style={{ width: '100%', display: 'grid', gridTemplateColumns: '1fr 132px', gap: 12, marginBottom: 22 }}>
          <Form.Item name="emailCode" style={{ marginBottom: 0 }} rules={[{ required: true, message: t('register.rule.emailCode.required') }]}>
            <Input
              size="large"
              autoComplete="one-time-code"
              placeholder={t('register.emailCode')}
              prefix={<SvgIcon iconClass="validCode" size={14} style={authIconStyle} />}
              onPressEnter={() => form.submit()}
            />
          </Form.Item>
          <Button size="large" loading={sendingCode} disabled={countdown > 0 || (inviteRegisterEnabled && (inviteChecking || !inviteCodeValid))} onClick={handleSendCode}>
            {countdownText}
          </Button>
        </div>

        {captchaEnabled && (
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 25 }}>
            <Form.Item name="code" rules={[{ required: true, message: t('register.rule.code.required') }]} style={{ width: '63%', marginBottom: 0 }}>
              <Input
                size="large"
                autoComplete="off"
                placeholder={t('register.code')}
                prefix={<SvgIcon iconClass="validCode" size={14} style={authIconStyle} />}
                onPressEnter={() => form.submit()}
              />
            </Form.Item>
            <div style={{ width: '33%', height: 40 }}>
              {codeUrl ? (
                <img
                  src={codeUrl}
                  alt={t('register.code')}
                  style={{
                    width: '100%',
                    height: '100%',
                    display: 'block',
                    paddingLeft: 12,
                    boxSizing: 'border-box',
                    cursor: 'pointer'
                  }}
                  onClick={getCode}
                />
              ) : null}
            </div>
          </div>
        )}

        <Form.Item
          name="username"
          style={{ marginBottom: 22 }}
          rules={[
            { required: true, message: t('register.rule.username.required') },
            { min: 2, max: 20, message: t('register.rule.username.length', { min: 2, max: 20 }) }
          ]}
        >
          <Input
            size="large"
            autoComplete="username"
            placeholder={t('register.username')}
            prefix={<SvgIcon iconClass="user" size={14} style={authIconStyle} />}
          />
        </Form.Item>

        <Form.Item
          name="password"
          style={{ marginBottom: 22 }}
          rules={[
            { required: true, message: t('register.rule.password.required') },
            { min: 8, max: 30, message: t('register.rule.password.length', { min: 8, max: 30 }) },
            { pattern: PASSWORD_REGEX, message: t('register.rule.password.pattern') }
          ]}
        >
          <Input.Password
            size="large"
            autoComplete="new-password"
            placeholder={t('register.password')}
            prefix={<SvgIcon iconClass="password" size={14} style={authIconStyle} />}
            visibilityToggle={false}
            onPressEnter={() => form.submit()}
          />
        </Form.Item>

        <Form.Item
          name="confirmPassword"
          dependencies={['password']}
          style={{ marginBottom: 22 }}
          rules={[
            { required: true, message: t('register.rule.confirmPassword.required') },
            ({ getFieldValue }) => ({
              validator(_, value) {
                if (!value || getFieldValue('password') === value) {
                  return Promise.resolve();
                }
                return Promise.reject(new Error(t('register.rule.confirmPassword.equalToPassword')));
              }
            })
          ]}
        >
          <Input.Password
            size="large"
            autoComplete="new-password"
            placeholder={t('register.confirmPassword')}
            prefix={<SvgIcon iconClass="password" size={14} style={authIconStyle} />}
            visibilityToggle={false}
            onPressEnter={() => form.submit()}
          />
        </Form.Item>

        <Form.Item style={{ marginBottom: 0 }}>
          <Button type="primary" htmlType="submit" loading={loading} block size="large" style={{ height: 40 }}>
            {loading ? t('register.registering') : t('register.register')}
          </Button>
          <div style={{ marginTop: 12, textAlign: 'right' }}>
            <Link to="/login">{t('register.switchLoginPage')}</Link>
          </div>
        </Form.Item>
      </Form>
    </AuthPageShell>
  );
}

// infoq-scaffold-frontend-vue/src/views/register.vue
<template>
  <div class="register">
    <el-form ref="registerRef" :model="registerForm" :rules="registerRules" class="register-form">
      <div class="title-box">
        <h3 class="title">{{ title }}</h3>
        <lang-select />
      </div>
      <el-form-item v-if="inviteRegisterEnabled" prop="inviteCode">
        <el-input
          v-model="registerForm.inviteCode"
          type="text"
          size="large"
          auto-complete="off"
          :placeholder="proxy.$t('register.inviteCode')"
          @blur="handleInviteBlur"
          @input="handleInviteInput"
        >
          <template #prefix><svg-icon icon-class="password" class="el-input__icon input-icon" /></template>
        </el-input>
      </el-form-item>
      <el-form-item prop="email">
        <el-input v-model="registerForm.email" type="text" size="large" auto-complete="off" :placeholder="proxy.$t('register.email')">
          <template #prefix><svg-icon icon-class="email" class="el-input__icon input-icon" /></template>
        </el-input>
      </el-form-item>
      <el-form-item prop="emailCode">
        <div class="form-inline-group">
          <el-input
            v-model="registerForm.emailCode"
            size="large"
            auto-complete="off"
            :placeholder="proxy.$t('register.emailCode')"
            @keyup.enter="handleRegister"
          >
            <template #prefix><svg-icon icon-class="validCode" class="el-input__icon input-icon" /></template>
          </el-input>
          <el-button :loading="sendingCode" :disabled="sendCodeDisabled" size="large" class="secondary-btn" @click.prevent="handleSendCode">
            {{ countdownText }}
          </el-button>
        </div>
      </el-form-item>
      <el-form-item v-if="captchaEnabled" prop="code">
        <el-input
          v-model="registerForm.code"
          size="large"
          auto-complete="off"
          :placeholder="proxy.$t('register.code')"
          style="width: 63%"
          @keyup.enter="handleRegister"
        >
          <template #prefix><svg-icon icon-class="validCode" class="el-input__icon input-icon" /></template>
        </el-input>
        <div class="register-code">
          <img :src="codeUrl" class="register-code-img" @click="getCode" />
        </div>
      </el-form-item>
      <el-form-item prop="username">
        <el-input v-model="registerForm.username" type="text" size="large" auto-complete="off" :placeholder="proxy.$t('register.username')">
          <template #prefix><svg-icon icon-class="user" class="el-input__icon input-icon" /></template>
        </el-input>
      </el-form-item>
      <el-form-item prop="password">
        <el-input
          v-model="registerForm.password"
          type="password"
          size="large"
          auto-complete="off"
          :placeholder="proxy.$t('register.password')"
          @keyup.enter="handleRegister"
        >
          <template #prefix><svg-icon icon-class="password" class="el-input__icon input-icon" /></template>
        </el-input>
      </el-form-item>
      <el-form-item prop="confirmPassword">
        <el-input
          v-model="registerForm.confirmPassword"
          type="password"
          size="large"
          auto-complete="off"
          :placeholder="proxy.$t('register.confirmPassword')"
          @keyup.enter="handleRegister"
        >
          <template #prefix><svg-icon icon-class="password" class="el-input__icon input-icon" /></template>
        </el-input>
      </el-form-item>
      <el-form-item style="width: 100%">
        <el-button :loading="loading" size="large" type="primary" style="width: 100%" @click.prevent="handleRegister">
          <span v-if="!loading">{{ proxy.$t('register.register') }}</span>
          <span v-else>{{ proxy.$t('register.registering') }}</span>
        </el-button>
        <div style="float: right">
          <router-link class="link-type" :to="'/login'">{{ proxy.$t('register.switchLoginPage') }}</router-link>
        </div>
      </el-form-item>
    </el-form>
    <!--  底部  -->
    <div class="el-register-footer">
      <span>Copyright © 2018-2026 Pontus All Rights Reserved.</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { checkInviteCode, getCodeImg, register, sendEmailCode } from '@/api/login';
import { RegisterForm } from '@/api/types';
import { to } from 'await-to-js';
import { useI18n } from 'vue-i18n';
import { validEmail } from '@/utils/validate';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;

const title = import.meta.env.VITE_APP_TITLE;
const router = useRouter();

const { t } = useI18n();

const registerForm = ref<RegisterForm>({
  inviteCode: '',
  email: '',
  emailCode: '',
  username: '',
  password: '',
  confirmPassword: '',
  code: '',
  uuid: ''
});

type ValidatorCallback = (error?: Error) => void;
const PASSWORD_REGEX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

const equalToPassword = (_rule: unknown, value: string, callback: ValidatorCallback) => {
  if (registerForm.value.password !== value) {
    callback(new Error(t('register.rule.confirmPassword.equalToPassword')));
  } else {
    callback();
  }
};

const validateInviteCode = (_rule: unknown, value: string | undefined, callback: ValidatorCallback) => {
  if (!inviteRegisterEnabled.value) {
    callback();
    return;
  }
  if (!value) {
    callback(new Error(t('register.rule.inviteCode.required')));
    return;
  }
  if (!inviteCodeValid.value) {
    callback(new Error(t('register.rule.inviteCode.invalid')));
    return;
  }
  callback();
};

const registerRules: ElFormRules = {
  inviteCode: [{ required: true, validator: validateInviteCode, trigger: 'blur' }],
  email: [
    { required: true, trigger: 'blur', message: t('register.rule.email.required') },
    { type: 'email', trigger: 'blur', message: t('register.rule.email.invalid') }
  ],
  emailCode: [{ required: true, trigger: 'blur', message: t('register.rule.emailCode.required') }],
  username: [
    { required: true, trigger: 'blur', message: t('register.rule.username.required') },
    { min: 2, max: 20, message: t('register.rule.username.length', { min: 2, max: 20 }), trigger: 'blur' }
  ],
  password: [
    { required: true, trigger: 'blur', message: t('register.rule.password.required') },
    { min: 8, max: 30, message: t('register.rule.password.length', { min: 8, max: 30 }), trigger: 'blur' },
    { pattern: PASSWORD_REGEX, message: t('register.rule.password.pattern'), trigger: 'blur' }
  ],
  confirmPassword: [
    { required: true, trigger: 'blur', message: t('register.rule.confirmPassword.required') },
    { required: true, validator: equalToPassword, trigger: 'blur' }
  ],
  code: [{ required: true, trigger: 'change', message: t('register.rule.code.required') }]
};
const codeUrl = ref('');
const loading = ref(false);
const sendingCode = ref(false);
const countdown = ref(0);
const captchaEnabled = ref(true);
const inviteRegisterEnabled = ref(false);
const inviteCodeValid = ref(false);
const inviteChecking = ref(false);
const lastValidatedInviteCode = ref('');
const registerRef = ref<ElFormInstance>();
let countdownTimer: number | undefined;

const countdownText = computed(() => {
  if (countdown.value > 0) {
    return t('register.countdown', { seconds: countdown.value });
  }
  return sendingCode.value ? t('register.sendingCode') : t('register.sendCode');
});

const sendCodeDisabled = computed(() => {
  if (countdown.value > 0) {
    return true;
  }
  if (!inviteRegisterEnabled.value) {
    return false;
  }
  return inviteChecking.value || !inviteCodeValid.value;
});

const resetInviteValidation = () => {
  inviteCodeValid.value = false;
  lastValidatedInviteCode.value = '';
};

const handleInviteInput = () => {
  if (!inviteRegisterEnabled.value) {
    return;
  }
  resetInviteValidation();
};

const handleInviteBlur = async () => {
  if (!inviteRegisterEnabled.value) {
    return;
  }
  const inviteCode = registerForm.value.inviteCode?.trim();
  registerForm.value.inviteCode = inviteCode;
  if (!inviteCode) {
    resetInviteValidation();
    return;
  }
  if (inviteCodeValid.value && lastValidatedInviteCode.value === inviteCode) {
    return;
  }
  inviteChecking.value = true;
  const [err] = await to(checkInviteCode(inviteCode));
  inviteChecking.value = false;
  if (err) {
    resetInviteValidation();
    registerRef.value?.validateField?.('inviteCode');
    return;
  }
  inviteCodeValid.value = true;
  lastValidatedInviteCode.value = inviteCode;
};

const handleRegister = () => {
  registerRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      if (inviteRegisterEnabled.value && !inviteCodeValid.value) {
        return;
      }
      loading.value = true;
      const [err] = await to(register(registerForm.value));
      if (!err) {
        const username = registerForm.value.username;
        await ElMessageBox.alert('<span style="color: red; ">' + t('register.registerSuccess', { username }) + '</font>', '系统提示', {
          app: undefined,
          dangerouslyUseHTMLString: true,
          type: 'success'
        });
        await router.push('/login');
      } else {
        loading.value = false;
        if (captchaEnabled.value) {
          await getCode();
        }
      }
    }
  });
};

const startCountdown = () => {
  countdown.value = 60;
  if (countdownTimer) {
    window.clearInterval(countdownTimer);
  }
  countdownTimer = window.setInterval(() => {
    if (countdown.value <= 1) {
      countdown.value = 0;
      if (countdownTimer) {
        window.clearInterval(countdownTimer);
        countdownTimer = undefined;
      }
      return;
    }
    countdown.value -= 1;
  }, 1000);
};

const handleSendCode = async () => {
  if (inviteRegisterEnabled.value && !registerForm.value.inviteCode) {
    ElMessage.error(t('register.rule.inviteCode.required'));
    return;
  }
  if (inviteRegisterEnabled.value && !inviteCodeValid.value) {
    ElMessage.error(t('register.rule.inviteCode.invalid'));
    return;
  }
  if (!registerForm.value.email) {
    ElMessage.error(t('register.rule.email.required'));
    return;
  }
  if (!validEmail(registerForm.value.email)) {
    ElMessage.error(t('register.rule.email.invalid'));
    return;
  }
  if (captchaEnabled.value && !registerForm.value.code) {
    ElMessage.error(t('register.rule.code.required'));
    return;
  }
  sendingCode.value = true;
  const [err] = await to(
    sendEmailCode({
      inviteCode: registerForm.value.inviteCode,
      email: registerForm.value.email,
      scene: 'register',
      code: registerForm.value.code,
      uuid: registerForm.value.uuid
    })
  );
  sendingCode.value = false;
  if (!err) {
    ElMessage.success(t('register.codeSent'));
    registerForm.value.code = '';
    startCountdown();
  }
  if (captchaEnabled.value) {
    await getCode();
  }
};

const getCode = async () => {
  const res = await getCodeImg();
  const { data } = res;
  if (!data.registerEnabled || !data.mailEnabled) {
    await router.replace('/login');
    return;
  }
  inviteRegisterEnabled.value = data.inviteRegisterEnabled === true;
  if (!inviteRegisterEnabled.value) {
    registerForm.value.inviteCode = '';
    resetInviteValidation();
  }
  captchaEnabled.value = data.captchaEnabled === undefined ? true : data.captchaEnabled;
  if (captchaEnabled.value) {
    registerForm.value.code = '';
    codeUrl.value = 'data:image/gif;base64,' + data.img;
    registerForm.value.uuid = data.uuid;
  } else {
    registerForm.value.code = '';
    registerForm.value.uuid = '';
    codeUrl.value = '';
  }
};

onMounted(() => {
  getCode();
});

onBeforeUnmount(() => {
  if (countdownTimer) {
    window.clearInterval(countdownTimer);
  }
});
</script>

<style lang="scss" scoped>
.register {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100%;
  background-image: url('../assets/images/login-background.jpg');
  background-size: cover;
}

.title-box {
  display: flex;

  .title {
    margin: 0px auto 30px auto;
    text-align: center;
    color: #707070;
  }

  :deep(.lang-select--style) {
    line-height: 0;
    color: #7483a3;
  }
}

.register-form {
  border-radius: 6px;
  background: #ffffff;
  width: 400px;
  padding: 25px 25px 5px 25px;

  .el-input {
    height: 40px;

    input {
      height: 40px;
    }
  }

  .input-icon {
    height: 39px;
    width: 14px;
    margin-left: 0;
  }
}

.form-inline-group {
  width: 100%;
  display: grid;
  grid-template-columns: 1fr 132px;
  gap: 12px;
}

.secondary-btn {
  width: 132px;
}

.register-tip {
  font-size: 13px;
  text-align: center;
  color: #bfbfbf;
}

.register-code {
  width: 33%;
  height: 40px;
  float: right;

  img {
    cursor: pointer;
    vertical-align: middle;
  }
}

.el-register-footer {
  height: 40px;
  line-height: 40px;
  position: fixed;
  bottom: 0;
  width: 100%;
  text-align: center;
  color: #fff;
  font-family: Arial, serif;
  font-size: 12px;
  letter-spacing: 1px;
}

.register-code-img {
  height: 40px;
  padding-left: 12px;
}
</style>
