// infoq-scaffold-frontend-react/src/pages/monitor/dataSource/index.tsx
import { useEffect, useMemo, useState } from 'react';
import { Alert, Card, Col, Empty, Progress, Row, Space, Statistic, Table, Tag, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { DatabaseOutlined, LinkOutlined, LoadingOutlined } from '@ant-design/icons';
import { getDataSourceMonitor } from '@/api/monitor/dataSource';
import type { DataSourceMonitorSummary, DataSourceMonitorVO, DataSourcePoolVO } from '@/api/monitor/dataSource/types';
import modal from '@/utils/modal';

const createDefaultSummary = (): DataSourceMonitorSummary => ({
  dataSourceCount: 0,
  activeConnections: 0,
  idleConnections: 0,
  totalConnections: 0,
  maximumPoolSize: 0,
  threadsAwaitingConnection: 0
});

const createDefaultMonitor = (): DataSourceMonitorVO => ({
  summary: createDefaultSummary(),
  items: []
});

const normalizePool = (pool?: Partial<DataSourcePoolVO>): DataSourcePoolVO => ({
  name: pool?.name ?? '',
  dbType: pool?.dbType ?? '',
  metricsReady: pool?.metricsReady ?? false,
  running: pool?.running ?? false,
  activeConnections: pool?.activeConnections ?? null,
  idleConnections: pool?.idleConnections ?? null,
  totalConnections: pool?.totalConnections ?? null,
  threadsAwaitingConnection: pool?.threadsAwaitingConnection ?? null,
  maximumPoolSize: pool?.maximumPoolSize ?? null,
  usagePercent: pool?.usagePercent ?? null,
  state: pool?.state ?? 'UNINITIALIZED'
});

const normalizeMonitor = (value?: Partial<DataSourceMonitorVO> | null): DataSourceMonitorVO => {
  if (!Array.isArray(value?.items)) {
    throw new Error('连接池监控响应 items 必须是数组');
  }
  return {
    summary: {
      ...createDefaultSummary(),
      ...(value?.summary ?? {})
    },
    items: value.items.map((item) => normalizePool(item))
  };
};

const displayText = (value?: string | null) => value || '-';

const displayCount = (value?: number | null) => (value ?? 0).toString();

const formatPercent = (value?: number | null) => `${Number(value ?? 0).toFixed(2)}%`;

const getStateMeta = (state?: string) =>
  (
    ({
      RUNNING: { label: '运行中', color: 'success' },
      BUSY: { label: '繁忙', color: 'orange' },
      SATURATED: { label: '饱和', color: 'error' },
      UNINITIALIZED: { label: '未初始化', color: 'default' }
    }) as Record<string, { label: string; color: string }>
  )[state || ''] || { label: state || '-', color: 'default' };

export default function DataSourcePage() {
  const [monitor, setMonitor] = useState<DataSourceMonitorVO>(createDefaultMonitor);
  const [errorMessage, setErrorMessage] = useState('');

  useEffect(() => {
    const loadMonitor = async () => {
      modal.loading('正在加载连接池监控数据，请稍候！');
      setErrorMessage('');
      try {
        const response = await getDataSourceMonitor();
        setMonitor(normalizeMonitor(response.data));
      } catch (error) {
        setErrorMessage(error instanceof Error ? error.message : '加载连接池监控数据失败');
      } finally {
        modal.closeLoading();
      }
    };

    loadMonitor();
  }, []);

  const columns = useMemo<ColumnsType<DataSourcePoolVO>>(
    () => [
      {
        title: '数据源',
        dataIndex: 'name',
        key: 'name',
        width: 180,
        render: (_, record) => (
          <Space orientation="vertical" size={2}>
            <Typography.Text strong>{displayText(record.name)}</Typography.Text>
            <Typography.Text type="secondary">{displayText(record.dbType)}</Typography.Text>
          </Space>
        )
      },
      {
        title: '状态',
        dataIndex: 'state',
        key: 'state',
        width: 140,
        render: (value: string, record) => {
          const meta = getStateMeta(value);
          return (
            <Space orientation="vertical" size={4}>
              <Tag color={meta.color}>{meta.label}</Tag>
              <Typography.Text type="secondary">{record.running ? '连接池已启动' : '连接池未启动'}</Typography.Text>
            </Space>
          );
        }
      },
      {
        title: '连接概览',
        key: 'connections',
        width: 170,
        render: (_, record) => (
          <Space orientation="vertical" size={2}>
            <span>活跃 {displayCount(record.activeConnections)}</span>
            <span>空闲 {displayCount(record.idleConnections)}</span>
            <span>总数 {displayCount(record.totalConnections)}</span>
          </Space>
        )
      },
      {
        title: '池容量',
        key: 'capacity',
        width: 160,
        render: (_, record) => (
          <Space orientation="vertical" size={2}>
            <span>最大 {displayCount(record.maximumPoolSize)}</span>
            <span>等待 {displayCount(record.threadsAwaitingConnection)}</span>
          </Space>
        )
      },
      {
        title: '等待线程',
        dataIndex: 'threadsAwaitingConnection',
        key: 'threadsAwaitingConnection',
        width: 110,
        align: 'center',
        render: (value: number | null) => displayCount(value)
      },
      {
        title: '占用率',
        dataIndex: 'usagePercent',
        key: 'usagePercent',
        width: 180,
        render: (value: number | null) => {
          const usage = value ?? 0;
          return (
            <Space orientation="vertical" size={4} style={{ width: '100%' }}>
              <Typography.Text style={{ color: usage >= 80 ? '#cf1322' : undefined }}>{formatPercent(usage)}</Typography.Text>
              <Progress percent={usage} size="small" status={usage >= 90 ? 'exception' : undefined} />
            </Space>
          );
        }
      }
    ],
    []
  );

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {errorMessage ? <Alert type="error" showIcon title={errorMessage} /> : null}

      <Row gutter={[12, 12]}>
        <Col xs={12} md={6}>
          <Card hoverable>
            <Statistic title="数据源数" value={monitor.summary.dataSourceCount} prefix={<DatabaseOutlined />} />
          </Card>
        </Col>
        <Col xs={12} md={6}>
          <Card hoverable>
            <Statistic title="活跃连接" value={monitor.summary.activeConnections} prefix={<LinkOutlined />} />
          </Card>
        </Col>
        <Col xs={12} md={6}>
          <Card hoverable>
            <Statistic title="空闲连接" value={monitor.summary.idleConnections} prefix={<DatabaseOutlined />} />
          </Card>
        </Col>
        <Col xs={12} md={6}>
          <Card hoverable>
            <Statistic title="等待线程" value={monitor.summary.threadsAwaitingConnection} prefix={<LoadingOutlined />} />
          </Card>
        </Col>
      </Row>

      <Card hoverable title="连接池监控">
        <Table<DataSourcePoolVO>
          rowKey="name"
          columns={columns}
          dataSource={monitor.items}
          pagination={false}
          scroll={{ x: 1000 }}
          locale={{ emptyText: <Empty description="暂无连接池数据" /> }}
        />
      </Card>
    </Space>
  );
}

// infoq-scaffold-frontend-vue/src/views/monitor/dataSource/index.vue
<template>
  <div class="p-2 monitor-data-source-page">
    <el-alert v-if="errorMessage" :title="errorMessage" type="error" :closable="false" class="mb-[10px]" />

    <el-row :gutter="10" class="mb-[10px]">
      <el-col :xs="12" :md="6">
        <el-card shadow="hover" class="summary-card">
          <div class="summary-label">数据源数</div>
          <div class="summary-value">{{ monitor.summary.dataSourceCount }}</div>
        </el-card>
      </el-col>
      <el-col :xs="12" :md="6">
        <el-card shadow="hover" class="summary-card">
          <div class="summary-label">活跃连接</div>
          <div class="summary-value">{{ monitor.summary.activeConnections }}</div>
        </el-card>
      </el-col>
      <el-col :xs="12" :md="6">
        <el-card shadow="hover" class="summary-card">
          <div class="summary-label">空闲连接</div>
          <div class="summary-value">{{ monitor.summary.idleConnections }}</div>
        </el-card>
      </el-col>
      <el-col :xs="12" :md="6">
        <el-card shadow="hover" class="summary-card">
          <div class="summary-label">等待线程</div>
          <div class="summary-value">{{ monitor.summary.threadsAwaitingConnection }}</div>
        </el-card>
      </el-col>
    </el-row>

    <el-card shadow="hover">
      <template #header>
        <span>连接池监控</span>
      </template>

      <div v-if="monitor.items.length" class="monitor-table">
        <table>
          <thead>
            <tr>
              <th>数据源</th>
              <th>状态</th>
              <th>连接概览</th>
              <th>池容量</th>
              <th>等待线程</th>
              <th>占用率</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="pool in monitor.items" :key="pool.name">
              <td>
                <div class="font-semibold">{{ displayText(pool.name) }}</div>
                <div class="sub-text">{{ displayText(pool.dbType) }}</div>
              </td>
              <td>
                <el-tag :type="stateTagType(pool.state)">{{ stateLabel(pool.state) }}</el-tag>
                <div class="sub-text">{{ pool.running ? '连接池已启动' : '连接池未启动' }}</div>
              </td>
              <td>
                <div>活跃 {{ displayCount(pool.activeConnections) }}</div>
                <div>空闲 {{ displayCount(pool.idleConnections) }}</div>
                <div>总数 {{ displayCount(pool.totalConnections) }}</div>
              </td>
              <td>
                <div>最大 {{ displayCount(pool.maximumPoolSize) }}</div>
                <div>等待 {{ displayCount(pool.threadsAwaitingConnection) }}</div>
              </td>
              <td>{{ displayCount(pool.threadsAwaitingConnection) }}</td>
              <td class="usage-cell">
                <el-progress
                  :percentage="pool.usagePercent ?? 0"
                  :status="usageProgressStatus(pool.usagePercent)"
                  :stroke-width="12"
                  :show-text="false"
                />
                <div :class="dangerClass(pool.usagePercent)">{{ formatPercent(pool.usagePercent) }}</div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <el-empty v-else description="暂无连接池数据" />
    </el-card>
  </div>
</template>

<script setup name="DataSource" lang="ts">
import { getDataSourceMonitor } from '@/api/monitor/dataSource';
import type { DataSourceMonitorSummary, DataSourceMonitorVO, DataSourcePoolVO } from '@/api/monitor/dataSource/types';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;

const createDefaultSummary = (): DataSourceMonitorSummary => ({
  dataSourceCount: 0,
  activeConnections: 0,
  idleConnections: 0,
  totalConnections: 0,
  maximumPoolSize: 0,
  threadsAwaitingConnection: 0
});

const createDefaultMonitor = (): DataSourceMonitorVO => ({
  summary: createDefaultSummary(),
  items: []
});

const normalizePool = (pool?: Partial<DataSourcePoolVO>): DataSourcePoolVO => ({
  name: pool?.name ?? '',
  dbType: pool?.dbType ?? '',
  metricsReady: pool?.metricsReady ?? false,
  running: pool?.running ?? false,
  activeConnections: pool?.activeConnections ?? null,
  idleConnections: pool?.idleConnections ?? null,
  totalConnections: pool?.totalConnections ?? null,
  threadsAwaitingConnection: pool?.threadsAwaitingConnection ?? null,
  maximumPoolSize: pool?.maximumPoolSize ?? null,
  usagePercent: pool?.usagePercent ?? null,
  state: pool?.state ?? 'UNINITIALIZED'
});

const normalizeMonitor = (value?: Partial<DataSourceMonitorVO> | null): DataSourceMonitorVO => {
  if (!Array.isArray(value?.items)) {
    throw new Error('连接池监控响应 items 必须是数组');
  }
  return {
    summary: {
      ...createDefaultSummary(),
      ...(value?.summary ?? {})
    },
    items: value.items.map((item) => normalizePool(item))
  };
};

const monitor = ref<DataSourceMonitorVO>(createDefaultMonitor());
const errorMessage = ref('');

const displayText = (value?: string | null) => value || '-';

const displayCount = (value?: number | null) => (value ?? 0).toString();

const formatPercent = (value?: number | null) => `${Number(value ?? 0).toFixed(2)}%`;

const stateLabel = (state?: string) =>
  (
    ({
      RUNNING: '运行中',
      BUSY: '繁忙',
      SATURATED: '饱和',
      UNINITIALIZED: '未初始化'
    }) as Record<string, string>
  )[state || ''] ||
  state ||
  '-';

const stateTagType = (state?: string) =>
  (
    ({
      RUNNING: 'success',
      BUSY: 'warning',
      SATURATED: 'danger',
      UNINITIALIZED: 'info'
    }) as Record<string, string>
  )[state || ''] || 'info';

const usageProgressStatus = (value?: number | null) => {
  const usage = value ?? 0;
  if (usage >= 90) {
    return 'exception';
  }
  if (usage >= 80) {
    return 'warning';
  }
  return 'success';
};

const dangerClass = (value?: number | null) => ((value ?? 0) >= 80 ? 'text-danger' : '');

const loadMonitor = async () => {
  proxy?.$modal.loading('正在加载连接池监控数据，请稍候！');
  errorMessage.value = '';
  try {
    const res = await getDataSourceMonitor();
    monitor.value = normalizeMonitor(res.data);
  } catch (error) {
    errorMessage.value = error instanceof Error ? error.message : '加载连接池监控数据失败';
  } finally {
    proxy?.$modal.closeLoading();
  }
};

onMounted(() => {
  loadMonitor();
});
</script>

<style scoped lang="scss">
.summary-card {
  height: 100%;
}

.summary-label {
  color: var(--el-text-color-secondary);
  font-size: 13px;
}

.summary-value {
  margin-top: 8px;
  color: var(--el-text-color-primary);
  font-size: 28px;
  font-weight: 700;
}

.monitor-table table {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
}

.monitor-table td,
.monitor-table th {
  padding: 12px 10px;
  border: 1px solid var(--el-border-color-lighter);
  vertical-align: top;
  word-break: break-all;
}

.monitor-table th {
  color: var(--el-text-color-secondary);
  background: var(--el-fill-color-light);
  font-weight: 600;
}

.sub-text {
  margin-top: 4px;
  color: var(--el-text-color-secondary);
  font-size: 12px;
}

.usage-cell {
  min-width: 140px;
}

.text-danger {
  color: var(--el-color-danger);
  font-weight: 600;
}
</style>
