// infoq-scaffold-frontend-weapp-react/src/pages/system-menus/index.tsx
import {View} from '@tarojs/components';
import Taro, {useDidShow} from '@tarojs/taro';
import {
  assertArrayData,
  delMenu,
  type DictOption,
  flattenTree,
  type FlatTreeItem,
  getDictLabel,
  getDicts,
  listMenu,
  type MenuQuery,
  type MenuVO,
  toDictOptions
} from '@/api';
import {useState} from 'react';
import {AtButton, AtInput} from 'taro-ui';
import BottomNav from '../../components/bottom-nav';
import {EmptyNotice, FabButton, KeyValueList, RecordCard, StatusTag} from '../../components/taro-ui-kit';
import {navigate, routes} from '../../utils/navigation';
import {handlePageError, showSuccess} from '../../utils/ui';
import {useSessionStore} from '../../store/session';
import './index.scss';

const menuTypeOptions = [
  { label: '目录', value: 'M' },
  { label: '菜单', value: 'C' },
  { label: '按钮', value: 'F' }
];

const createQuery = (): MenuQuery => ({
  menuName: '',
  status: ''
});

export default function SystemMenusPage() {
  const permissions = useSessionStore((state) => state.permissions);
  const loadSession = useSessionStore((state) => state.loadSession);
  const [query, setQuery] = useState<MenuQuery>(createQuery());
  const [list, setList] = useState<Array<FlatTreeItem<MenuVO>>>([]);
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);

  const canList = permissions.includes('system:menu:list');
  const canAdd = permissions.includes('system:menu:add');
  const canEdit = permissions.includes('system:menu:edit');
  const canRemove = permissions.includes('system:menu:remove');

  const loadPage = async (nextQuery = query) => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }
      const [statusResponse, listResponse] = await Promise.all([
        getDicts('sys_normal_disable'),
        canList ? listMenu(nextQuery) : Promise.resolve({ data: [] as MenuVO[] })
      ]);
      setStatusOptions(toDictOptions(statusResponse.data));
      setList(flattenTree(assertArrayData(listResponse.data, '菜单列表响应 data')));
    } catch (error) {
      await handlePageError(error, '菜单列表加载失败');
    }
  };

  useDidShow(() => {
    void loadPage();
  });

  const openCreate = (parentId?: string | number) => {
    navigate(`${routes.menuForm}${parentId !== undefined ? `?parentId=${parentId}` : ''}`);
  };

  const openEdit = (menuId: string | number) => {
    navigate(`${routes.menuForm}?menuId=${menuId}`);
  };

  const handleDelete = async (menuId: string | number) => {
    const modal = await Taro.showModal({
      title: '确认删除',
      content: `确定删除菜单 #${menuId} 吗？`
    });
    if (!modal.confirm) return;
    try {
      await delMenu(menuId);
      await showSuccess('菜单已删除');
      await loadPage({ ...query });
    } catch (error) {
      await handlePageError(error, '菜单删除失败');
    }
  };

  return (
    <View className="list-container">
      <View className="search-section">
        <View className="search-card">
          <AtInput
            clear
            name="menuName"
            placeholder="按菜单名称过滤"
            title="菜单名称"
            value={query.menuName || ''}
            onChange={(value) => {
              setQuery((prev) => ({ ...prev, menuName: String(value) }));
              return value;
            }}
          />
          <View className="search-actions">
            <AtButton
              className="search-action-btn"
              type="secondary"
              onClick={() => {
                const nextQuery = createQuery();
                setQuery(nextQuery);
                void loadPage(nextQuery);
              }}
            >
              重置
            </AtButton>
            <AtButton
              className="search-action-btn"
              type="primary"
              onClick={() => void loadPage({ ...query })}
            >
              查询
            </AtButton>
          </View>
        </View>
      </View>

      <View className="list-content">
        {!canList && <EmptyNotice message="当前账号没有访问权限" />}
        {canList && list.length === 0 && <EmptyNotice message="未查询到相关菜单" />}
        {canList && list.map((item) => (
          <RecordCard
            key={String(item.menuId)}
            icon="menu"
            title={`${'· '.repeat(item._depth)}${item.menuName}`}
            statusColor={item.status === '0' ? '#52c41a' : '#ff4d4f'}
            extra={
              <StatusTag
                label={menuTypeOptions.find(o => o.value === item.menuType)?.label || '未知'}
                type={item.menuType === 'M' ? 'info' : item.menuType === 'C' ? 'success' : 'warning'}
              />
            }
            actions={[
              ...(canAdd ? [{ onClick: () => openCreate(item.menuId), title: '新增下级' }] : []),
              ...(canEdit ? [{ onClick: () => void openEdit(item.menuId), title: '编辑' }] : []),
              ...(canRemove ? [{
                onClick: () => void handleDelete(item.menuId),
                title: '删除',
                danger: true
              }] : [])
            ]}
          >
            <KeyValueList
              items={[
                { label: '权限标识', value: item.perms || '-' },
                { label: '路由地址', value: item.path || '-' },
                { label: '状态', value: <StatusTag label={getDictLabel(statusOptions, item.status) || '正常'} type={item.status === '0' ? 'success' : 'error'} /> }
              ]}
            />
          </RecordCard>
        ))}
      </View>

      {canAdd && <FabButton onClick={() => openCreate()} />}

      <BottomNav active="admin" />
    </View>
  );
}

// infoq-scaffold-frontend-weapp-vue/src/pages/system-menus/index.vue
<template>
  <view class="list-container">
    <view class="search-section">
      <view class="search-card">
        <view class="search-field">
          <text class="field-label">菜单名称</text>
          <view class="field-input-box">
            <input v-model="query.menuName" placeholder="按菜单名称过滤" placeholder-style="color: #94a3b8" />
          </view>
        </view>
        <view class="search-actions">
  <button class="secondary-btn search-action-btn" @click="handleReset">重置</button>
  <button class="primary-btn search-action-btn" @click="handleSearch">查询</button>
</view>
      </view>
    </view>

    <view class="list-content">
      <EmptyNotice v-if="!canList" message="暂无访问权限" />
      <EmptyNotice v-else-if="filteredRows.length === 0" message="未查询到相关菜单" />

      <template v-if="canList">
        <RecordCard
          v-for="item in filteredRows"
          :key="String(item.menuId)"
          icon="menu"
          :title="item.menuName"
          :actions="getActions(item)"
        >
          <template #extra>
            <StatusTag
              :label="item.status === '0' ? '显示' : '隐藏'"
              :type="item.status === '0' ? 'success' : 'error'"
            />
          </template>

          <KeyValueList
            :items="[
              { label: '菜单类型', value: getMenuTypeLabel(item.menuType) },
              { label: '权限标识', value: item.perms || '-' },
              { label: '路由地址', value: item.path || '-' }
            ]"
          />
        </RecordCard>
      </template>
    </view>

    <FabButton v-if="canAdd" @click="openCreate" />

    <BottomNav active="admin" />
  </view>
</template>

<script setup lang="ts">
import {computed, reactive, ref} from 'vue';
import {onShow} from '@dcloudio/uni-app';
import {assertArrayData, delMenu, listMenu, type MenuVO} from '@/api';
import {ensureAuthenticated} from '@/composables/use-auth-guard';
import {navigate, routes} from '@/utils/navigation';
import {handlePageError, showSuccess} from '@/utils/ui';
import {useSessionStore} from '@/store/session';

import BottomNav from '@/components/BottomNav.vue';
import EmptyNotice from '@/components/EmptyNotice.vue';
import KeyValueList from '@/components/KeyValueList.vue';
import RecordCard from '@/components/RecordCard.vue';
import StatusTag from '@/components/StatusTag.vue';
import FabButton from '@/components/FabButton.vue';

const sessionStore = useSessionStore();
const rows = ref<MenuVO[]>([]);
const query = reactive({
  menuName: '',
  status: ''
});

const canList = computed(() => sessionStore.permissions.includes('system:menu:list'));
const canAdd = computed(() => sessionStore.permissions.includes('system:menu:add'));
const canEdit = computed(() => sessionStore.permissions.includes('system:menu:edit'));
const canRemove = computed(() => sessionStore.permissions.includes('system:menu:remove'));

const filteredRows = computed(() => {
  if (!query.menuName) return rows.value;
  const filter = query.menuName.toLowerCase();
  return rows.value.filter(r => r.menuName.toLowerCase().includes(filter));
});

const getMenuTypeLabel = (type: string) => {
  const map: Record<string, string> = { M: '目录', C: '菜单', F: '按钮' };
  return map[type] || type;
};

const loadData = async () => {
  if (!ensureAuthenticated()) return;
  try {
    await sessionStore.loadSession();
    const response = await listMenu();
    rows.value = assertArrayData(response.data, '菜单列表响应 data');
  } catch (error) {
    await handlePageError(error, '菜单加载失败');
  }
};

const handleSearch = () => {
  void loadData();
};

const handleReset = () => {
  query.menuName = '';
  void loadData();
};

const openCreate = () => navigate(routes.menuForm);

const getActions = (item: MenuVO) => {
  const actions = [];
  if (canEdit.value) {
    actions.push({ title: '编辑', onClick: () => navigate(`${routes.menuForm}?menuId=${item.menuId}`) });
  }
  if (canRemove.value) {
    actions.push({ title: '删除', danger: true, onClick: () => removeItem(item.menuId) });
  }
  return actions;
};

const removeItem = async (menuId: string | number) => {
  const res = await uni.showModal({ title: '确认删除', content: '确定删除该菜单项吗？' });
  if (!res.confirm) return;
  try {
    await delMenu(menuId);
    await showSuccess('删除成功');
    await loadData();
  } catch (error) {
    await handlePageError(error, '删除失败');
  }
};

onShow(() => {
  void loadData();
});
</script>

<style lang="scss">
@import './index.scss';
</style>
