// infoq-scaffold-frontend-weapp-vue/src/pages/system-depts/form/index.vue
<template>
  <view class="page-wrap">
    <view class="form-section">
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">基本信息</text>
        </view>
        <view class="card-content" style="padding: 0">
          <picker
            mode="selector"
            :range="deptTreeOptions.map(d => `${'· '.repeat(d._depth)}${d.label}`)"
            @change="handleParentDeptChange"
          >
            <view class="picker-input-aligned">
              <text class="picker-label">上级部门</text>
              <view class="picker-value-container">
                <text :class="['picker-value', !selectedParentDept ? 'placeholder' : '']">
                  {{ selectedParentDeptLabel }}
                </text>
                <AppIcon name="chevron-right" size="32" class="picker-arrow" />
              </view>
            </view>
          </picker>

          <view class="form-item-modern">
            <text class="form-label">部门名称</text>
            <input class="form-input-plain" v-model="form.deptName" placeholder="请输入部门名称" placeholder-style="color: #94a3b8" />
          </view>
          <view class="form-item-modern">
            <text class="form-label">负责人</text>
            <input class="form-input-plain" v-model="form.leader" placeholder="请输入负责人姓名" placeholder-style="color: #94a3b8" />
          </view>
          <view class="form-item-modern">
            <text class="form-label">联系电话</text>
            <input class="form-input-plain" v-model="form.phone" placeholder="请输入联系电话" placeholder-style="color: #94a3b8" />
          </view>
          <view class="form-item-modern">
            <text class="form-label">显示排序</text>
            <input class="form-input-plain" v-model.number="form.orderNum" type="number" placeholder="请输入排序" placeholder-style="color: #94a3b8" />
          </view>
        </view>
      </view>

      <view class="card-container">
        <view class="card-header">
          <text class="card-title">部门状态</text>
        </view>
        <view class="card-content">
          <view class="form-item-vertical">
            <text class="item-label">状态</text>
            <view class="radio-options-horizontal">
              <view
                v-for="item in statusOptions"
                :key="item.value"
                :class="['radio-option-item', form.status === item.value ? 'active' : '']"
                @click="form.status = item.value"
              >
                <view class="radio-circle">
                  <view v-if="form.status === item.value" class="radio-inner" />
                </view>
                <text class="radio-label">{{ item.label }}</text>
              </view>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- 操作按钮 -->
    <view class="action-section">
      <button class="primary-btn save-btn" :loading="submitting" @click="save">保 存</button>
      <button class="secondary-btn cancel-btn" @click="backOr(routes.depts)">取 消</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import {computed, reactive, ref} from 'vue';
import {onLoad} from '@dcloudio/uni-app';
import AppIcon from '@/components/AppIcon.vue';
import {
  addDept,
  assertArrayData,
  assertObjectData,
  type DeptForm,
  type DeptVO,
  type DictOption,
  flattenTree,
  type FlatTreeItem,
  getDept,
  getDicts,
  listDept,
  toDictOptions,
  updateDept
} from '@/api';
import {handleDeptTree} from '@/utils/helpers';
import {ensureAuthenticated, ensurePermission} from '@/composables/use-auth-guard';
import {backOr, routes} from '@/utils/navigation';
import {handlePageError, showSuccess} from '@/utils/ui';
import {useSessionStore} from '@/store/session';

type PickerChangeEvent = { detail?: { value?: string | number } };
type RawDeptNode = {
  id?: string | number;
  deptId?: string | number;
  label?: string;
  deptName?: string;
  parentId?: string | number;
  children?: RawDeptNode[];
};
type DeptTreeOption = {
  id: string | number;
  label: string;
  children?: DeptTreeOption[];
};

const normalizeDeptNode = (node: RawDeptNode): DeptTreeOption => ({
  id: node.id ?? node.deptId ?? '',
  label: node.label ?? node.deptName ?? String(node.id ?? node.deptId ?? ''),
  children: Array.isArray(node.children) ? node.children.map((child) => normalizeDeptNode(child)) : []
});

const sessionStore = useSessionStore();
const deptId = ref('');
const submitting = ref(false);
const statusOptions = ref<DictOption[]>([]);
const deptTreeOptions = ref<Array<FlatTreeItem<DeptTreeOption>>>([]);

const form = reactive<DeptForm>({
  parentId: 0,
  deptName: '',
  orderNum: 0,
  leader: '',
  phone: '',
  email: '',
  status: '0'
});

const isEdit = computed(() => Boolean(deptId.value));

const selectedParentDept = computed(() => deptTreeOptions.value.find(d => Number(d.id) === form.parentId));
const selectedParentDeptLabel = computed(() => selectedParentDept.value ? `${'· '.repeat(selectedParentDept.value._depth)}${selectedParentDept.value.label}` : '选择上级部门');

const handleParentDeptChange = (event: PickerChangeEvent) => {
  const index = Number(event.detail?.value);
  const target = Number.isInteger(index) ? deptTreeOptions.value[index] : undefined;
  if (!target) {
    return;
  }
  form.parentId = Number(target.id);
};

const loadData = async () => {
  try {
    const [statusRes, deptRes] = await Promise.all([
      getDicts('sys_normal_disable'),
      listDept()
    ]);

    statusOptions.value = toDictOptions(statusRes.data);

    // Add a virtual root node for "None" or "Root"
    const depts = assertArrayData(deptRes.data, '部门列表响应 data') as DeptVO[];
    const tree = handleDeptTree(depts as Array<Record<string, unknown>>)
      .map((node) => normalizeDeptNode(node as unknown as RawDeptNode));
    deptTreeOptions.value = [
      { id: 0, label: '主类目', _depth: 0, children: [] },
      ...flattenTree(tree)
    ];

    if (deptId.value) {
      const response = await getDept(deptId.value);
      Object.assign(form, assertObjectData(response.data, '部门详情响应 data'));
    }
  } catch (error) {
    await handlePageError(error, '部门数据加载失败');
  }
};

const save = async () => {
  if (!form.deptName?.trim()) {
    await uni.showToast({ title: '部门名称不能为空', icon: 'none' });
    return;
  }
  submitting.value = true;
  try {
    if (!ensureAuthenticated()) return;
    await sessionStore.loadSession();
    if (isEdit.value) {
      form.deptId = Number(deptId.value);
      await updateDept(form);
    } else {
      await addDept(form);
    }
    await showSuccess('保存成功');
    backOr(routes.depts);
  } catch (error) {
    await handlePageError(error, '部门保存失败');
  } finally {
    submitting.value = false;
  }
};

onLoad((query) => {
  const initPage = async () => {
    if (!ensureAuthenticated()) return;

    deptId.value = String(query?.deptId || '').trim();
    if (deptId.value) {
      try {
        const allowed = await ensurePermission('system:dept:query', {
          fallbackRoute: routes.depts,
          failureMessage: '当前账号没有部门查询权限'
        });
        if (!allowed) {
          return;
        }
      } catch (error) {
        await handlePageError(error, '部门数据加载失败');
        return;
      }
    }

    await loadData();
  };

  void initPage();
});
</script>

<style lang="scss">
@import '@/styles/common.scss';
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/system-depts/form/index.tsx
import {Picker, Text, View} from '@tarojs/components';
import Taro, {useDidShow, useRouter} from '@tarojs/taro';
import {
  addDept,
  assertArrayData,
  type DeptForm,
  type DeptVO,
  type DictOption,
  flattenTree,
  type FlatTreeItem,
  getDept,
  getDicts,
  listDept,
  toDictOptions,
  updateDept
} from '@/api';
import {useState} from 'react';
import {AtButton, AtInput} from 'taro-ui';
import {handlePageError, showSuccess} from '../../../utils/ui';
import {useSessionStore} from '../../../store/session';
import {routes} from '../../../utils/navigation';
import './index.scss';

const createForm = (): DeptForm => ({
  parentId: 0,
  deptId: undefined,
  deptName: '',
  deptCategory: '',
  orderNum: 1,
  phone: '',
  email: '',
  status: '0'
});

type DeptParentOption = {
  id: string | number;
  label: string;
  _depth: number;
};

export default function DeptFormPage() {
  const router = useRouter();
  const deptId = router.params.deptId;
  const parentIdFromUrl = router.params.parentId;
  const loadSession = useSessionStore((state) => state.loadSession);
  const [form, setForm] = useState<DeptForm>(createForm());
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);
  const [treeOptions, setTreeOptions] = useState<Array<FlatTreeItem<DeptVO>>>([]);
  const [submitting, setSubmitting] = useState(false);

  const loadData = async () => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }

      const [statusRes, listRes] = await Promise.all([
        getDicts('sys_normal_disable'),
        listDept({ pageNum: 1, pageSize: 100, deptName: '', deptCategory: '', status: '' })
      ]);
      setStatusOptions(toDictOptions(statusRes.data));
      setTreeOptions(flattenTree(assertArrayData(listRes.data, '部门列表响应 data')));

      if (deptId) {
        const response = await getDept(deptId);
        const data = response.data;
        setForm({
          deptId: data.deptId,
          parentId: data.parentId,
          deptName: data.deptName,
          deptCategory: data.deptCategory || '',
          orderNum: data.orderNum,
          phone: data.phone || '',
          email: data.email || '',
          status: data.status || '0'
        });
      } else if (parentIdFromUrl) {
        setForm(prev => ({ ...prev, parentId: Number(parentIdFromUrl) }));
      }
    } catch (error) {
      await handlePageError(error, '加载失败');
    }
  };

  useDidShow(() => {
    void loadData();
  });

  const handleSave = async () => {
    if (!form.deptName?.trim()) {
      await Taro.showToast({ title: '请输入部门名称', icon: 'none' });
      return;
    }

    setSubmitting(true);
    try {
      if (deptId) {
        await updateDept(form);
      } else {
        await addDept(form);
      }
      await showSuccess(deptId ? '部门已更新' : '部门已创建');
      Taro.navigateBack();
    } catch (error) {
      await handlePageError(error, '保存失败');
    } finally {
      setSubmitting(false);
    }
  };

  const parentDeptOptions: DeptParentOption[] = [
    { label: '顶级部门', id: 0, _depth: 0 },
    ...treeOptions
      .filter((item) => String(item.deptId) !== String(deptId))
      .map((item) => ({
        id: item.deptId,
        label: item.deptName,
        _depth: item._depth
      }))
  ];

  const selectedParent = parentDeptOptions.find(d => String(d.id) === String(form.parentId));
  const selectedParentLabel = selectedParent ? `${'· '.repeat(selectedParent._depth)}${selectedParent.label}` : '请选择上级部门';

  return (
    <View className="dept-form-container">
      <View className="form-section">
        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">基本信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            <Picker
              mode="selector"
              range={parentDeptOptions.map((item) => `${'· '.repeat(item._depth)}${item.label}`)}
              onChange={(e) => {
                const index = Number(e.detail.value);
                setForm((prev) => ({ ...prev, parentId: parentDeptOptions[index]?.id ?? 0 }));
              }}
            >
              <View className="at-input picker-input-aligned">
                <View className="at-input__container">
                  <View className="at-input__title">上级部门</View>
                  <View className="at-input__input picker-value-container">
                    <Text className={`picker-value ${!selectedParent ? 'placeholder' : ''}`}>
                      {selectedParentLabel}
                    </Text>
                    <View className="at-icon at-icon-chevron-right picker-arrow"></View>
                  </View>
                </View>
              </View>
            </Picker>

            <AtInput
              name="deptName"
              title="部门名称"
              placeholder="请输入部门名称"
              value={form.deptName || ''}
              onChange={(v) => { setForm(p => ({ ...p, deptName: String(v) })); return v; }}
            />
            <AtInput
              name="deptCategory"
              title="部门类别"
              placeholder="请输入部门类别"
              value={form.deptCategory || ''}
              onChange={(v) => { setForm(p => ({ ...p, deptCategory: String(v) })); return v; }}
            />
            <AtInput
              name="orderNum"
              title="显示顺序"
              type="number"
              placeholder="请输入显示顺序"
              value={String(form.orderNum || 1)}
              onChange={(v) => { setForm(p => ({ ...p, orderNum: Number(v || 1) })); return v; }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">联系信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            <AtInput
              name="phone"
              title="联系电话"
              type="phone"
              placeholder="请输入联系电话"
              value={form.phone || ''}
              onChange={(v) => { setForm(p => ({ ...p, phone: String(v) })); return v; }}
            />
            <AtInput
              name="email"
              title="邮箱地址"
              placeholder="请输入邮箱地址"
              value={form.email || ''}
              onChange={(v) => { setForm(p => ({ ...p, email: String(v) })); return v; }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">状态</Text>
          </View>
          <View className="card-content">
            <View className="radio-options-horizontal">
              {statusOptions.map((item) => (
                <View
                  key={item.value}
                  className={`radio-option-item ${form.status === item.value ? 'active' : ''}`}
                  onClick={() => setForm((prev) => ({ ...prev, status: item.value }))}
                >
                  <View className="radio-circle">
                    {form.status === item.value && <View className="radio-inner" />}
                  </View>
                  <Text className="radio-label">{item.label}</Text>
                </View>
              ))}
            </View>
          </View>
        </View>
      </View>

      <View className="action-section">
        <AtButton className="save-btn" type="primary" loading={submitting} onClick={() => void handleSave()}>
          保存部门
        </AtButton>
        <AtButton className="cancel-btn" onClick={() => Taro.navigateBack()}>
          返回
        </AtButton>
      </View>
    </View>
  );
}
