// infoq-scaffold-frontend-react/src/pages/system/invite/index.tsx
import { useCallback, useEffect, useState } from 'react';
import { CloseCircleOutlined, DeleteOutlined, DownloadOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { Button, Card, Col, DatePicker, Form, Input, InputNumber, Modal, Row, Select, Space, Switch, Table, Tooltip, Typography } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import type { Dayjs } from 'dayjs';
import useDictOptions from '@/hooks/useDictOptions';
import { cancelInvite, delInvite, generateInvite, listInvite } from '@/api/system/invite';
import type { InviteCodeGenerateForm, InviteCodeQuery, InviteCodeVO } from '@/api/system/invite/types';
import Pagination from '@/components/Pagination';
import RightToolbar from '@/components/RightToolbar';
import DictTag from '@/components/DictTag';
import modal from '@/utils/modal';
import { addDateRange } from '@/utils/scaffold';
import { download } from '@/utils/request';

type GenerateInviteFormState = InviteCodeGenerateForm & {
  expireTime?: Dayjs;
  permanent: boolean;
};

type CancelInviteFormState = {
  inviteId?: number | string;
  canceledReason: string;
};

const initialQuery: InviteCodeQuery = {
  pageNum: 1,
  pageSize: 10,
  inviteCode: '',
  status: '',
  usedUserEmail: '',
  creatorName: ''
};

const initialGenerateForm: GenerateInviteFormState = {
  generateCount: 1,
  expireTime: undefined,
  remark: '',
  permanent: true
};

const initialCancelForm: CancelInviteFormState = {
  inviteId: undefined,
  canceledReason: ''
};

const formatRange = (range: [Dayjs, Dayjs] | null) =>
  range ? [range[0].format('YYYY-MM-DD HH:mm:ss'), range[1].format('YYYY-MM-DD HH:mm:ss')] : [];

export default function InvitePage() {
  const [query, setQuery] = useState<InviteCodeQuery>(initialQuery);
  const [dateRange, setDateRange] = useState<[Dayjs, Dayjs] | null>(null);
  const [loading, setLoading] = useState(false);
  const [showSearch, setShowSearch] = useState(true);
  const [list, setList] = useState<InviteCodeVO[]>([]);
  const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<Array<string | number>>([]);
  const [selectedRows, setSelectedRows] = useState<InviteCodeVO[]>([]);
  const [generateDialogOpen, setGenerateDialogOpen] = useState(false);
  const [cancelDialogOpen, setCancelDialogOpen] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [generateForm] = Form.useForm<GenerateInviteFormState>();
  const [cancelForm] = Form.useForm<CancelInviteFormState>();
  const generatePermanent = Form.useWatch('permanent', generateForm) ?? true;
  const dict = useDictOptions('sys_invite_code_status');

  const loadList = useCallback(async (nextQuery: InviteCodeQuery = query, nextRange: [Dayjs, Dayjs] | null = dateRange) => {
    setLoading(true);
    try {
      const response = await listInvite(addDateRange({ ...nextQuery }, formatRange(nextRange)));
      setList(response.rows);
      setTotal(response.total ?? response.rows.length);
    } finally {
      setLoading(false);
    }
  }, [dateRange, query]);

  useEffect(() => {
    loadList(initialQuery, null);
  }, [loadList]);

  const canCancel = (record: InviteCodeVO) => record.status === '0';
  const canDelete = (record: InviteCodeVO) => record.status !== '1';

  const columns: ColumnsType<InviteCodeVO> = [
    {
      title: '邀请码',
      dataIndex: 'inviteCode',
      width: 260,
      align: 'center',
      render: (value: string) => (
        <Typography.Text copyable={{ text: value, onCopy: () => modal.msgSuccess('邀请码已复制') }} style={{ fontFamily: 'Consolas, Monaco, monospace' }}>
          {value}
        </Typography.Text>
      )
    },
    {
      title: '总状态',
      dataIndex: 'status',
      width: 120,
      align: 'center',
      render: (value: string) => <DictTag options={dict.sys_invite_code_status || []} value={value} />
    },
    {
      title: '使用人邮箱',
      dataIndex: 'usedUserEmail',
      width: 180,
      align: 'center',
      ellipsis: true
    },
    {
      title: '生成人',
      dataIndex: 'creatorName',
      width: 140,
      align: 'center',
      ellipsis: true
    },
    {
      title: '生成时间',
      dataIndex: 'createTime',
      width: 180,
      align: 'center'
    },
    {
      title: '过期时间',
      dataIndex: 'expireTime',
      width: 180,
      align: 'center'
    },
    {
      title: '使用时间',
      dataIndex: 'usedTime',
      width: 180,
      align: 'center'
    },
    {
      title: '作废时间',
      dataIndex: 'canceledTime',
      width: 180,
      align: 'center'
    },
    {
      title: '备注',
      dataIndex: 'remark',
      align: 'center',
      ellipsis: true
    },
    {
      title: '作废原因',
      dataIndex: 'canceledReason',
      align: 'center',
      ellipsis: true
    },
    {
      title: '操作',
      key: 'action',
      width: 140,
      align: 'center',
      render: (_, record) => (
        <Space size={4}>
          <Tooltip title="作废">
            <Button
              className="table-action-link"
              type="link"
              icon={<CloseCircleOutlined />}
              disabled={!canCancel(record)}
              onClick={() => openCancelDialog(record)}
            />
          </Tooltip>
          <Tooltip title="删除">
            <Button
              className="table-action-link"
              type="link"
              icon={<DeleteOutlined />}
              disabled={!canDelete(record)}
              onClick={() => handleDelete(record)}
            />
          </Tooltip>
        </Space>
      )
    }
  ];

  const handleSearch = () => {
    const next = { ...query, pageNum: 1 };
    setQuery(next);
    loadList(next, dateRange);
  };

  const handleReset = () => {
    setQuery(initialQuery);
    setDateRange(null);
    loadList(initialQuery, null);
  };

  const openGenerateDialog = () => {
    generateForm.setFieldsValue(initialGenerateForm);
    setGenerateDialogOpen(true);
  };

  const closeGenerateDialog = () => {
    setGenerateDialogOpen(false);
    generateForm.resetFields();
  };

  const resolveCancelRecord = (record?: InviteCodeVO) => {
    const target = record ?? selectedRows[0];
    if (!target) {
      modal.msgWarning('请选择需要作废的邀请码');
      return undefined;
    }
    if (!canCancel(target)) {
      modal.msgWarning('仅未使用的邀请码允许作废');
      return undefined;
    }
    return target;
  };

  const openCancelDialog = (record?: InviteCodeVO) => {
    const target = resolveCancelRecord(record);
    if (!target) {
      return;
    }
    cancelForm.setFieldsValue({
      ...initialCancelForm,
      inviteId: target.inviteId
    });
    setCancelDialogOpen(true);
  };

  const closeCancelDialog = () => {
    setCancelDialogOpen(false);
    cancelForm.resetFields();
  };

  const handleGenerateSubmit = async () => {
    const values = await generateForm.validateFields();
    setSubmitting(true);
    try {
      await generateInvite({
        generateCount: values.generateCount,
        expireTime: values.permanent ? undefined : values.expireTime?.format('YYYY-MM-DD HH:mm:ss'),
        remark: values.remark
      });
      modal.msgSuccess('生成成功');
      closeGenerateDialog();
      loadList(query, dateRange);
    } finally {
      setSubmitting(false);
    }
  };

  const handleCancelSubmit = async () => {
    const values = await cancelForm.validateFields();
    if (!values.inviteId) {
      return;
    }
    setSubmitting(true);
    try {
      await cancelInvite({
        inviteId: values.inviteId,
        canceledReason: values.canceledReason
      });
      modal.msgSuccess('作废成功');
      closeCancelDialog();
      loadList(query, dateRange);
    } finally {
      setSubmitting(false);
    }
  };

  const handleDelete = async (record?: InviteCodeVO) => {
    const targets = record ? [record] : selectedRows;
    if (!targets.length) {
      modal.msgWarning('请选择需要删除的邀请码');
      return;
    }
    if (targets.some((item) => !canDelete(item))) {
      modal.msgWarning('已使用的邀请码不允许删除');
      return;
    }
    const confirmed = await modal.confirm(`是否确认删除邀请码 "${targets.map((item) => item.inviteCode).join('、')}" ?`);
    if (!confirmed) {
      return;
    }
    await delInvite(record ? record.inviteId : selectedIds);
    modal.msgSuccess('删除成功');
    setSelectedIds([]);
    setSelectedRows([]);
    loadList(query, dateRange);
  };

  return (
    <Space orientation="vertical" size={12} style={{ width: '100%' }}>
      {showSearch && (
        <Card>
          <Form layout="inline" className="query-form">
            <Row gutter={16} style={{ width: '100%' }}>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="邀请码" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入邀请码"
                    value={query.inviteCode}
                    onChange={(event) => setQuery((prev) => ({ ...prev, inviteCode: event.target.value }))}
                    onPressEnter={handleSearch}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="总状态" style={{ width: '100%', marginBottom: 12 }}>
                  <Select
                    allowClear
                    placeholder="请选择状态"
                    style={{ width: '100%' }}
                    value={query.status || undefined}
                    options={(dict.sys_invite_code_status || []).map((item) => ({ label: item.label, value: item.value }))}
                    onChange={(value) => setQuery((prev) => ({ ...prev, status: value || '' }))}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="使用人邮箱" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入使用人邮箱"
                    value={query.usedUserEmail}
                    onChange={(event) => setQuery((prev) => ({ ...prev, usedUserEmail: event.target.value }))}
                    onPressEnter={handleSearch}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={6}>
                <Form.Item label="生成人" style={{ width: '100%', marginBottom: 12 }}>
                  <Input
                    allowClear
                    placeholder="请输入生成人"
                    value={query.creatorName}
                    onChange={(event) => setQuery((prev) => ({ ...prev, creatorName: event.target.value }))}
                    onPressEnter={handleSearch}
                  />
                </Form.Item>
              </Col>
              <Col xs={24} md={12} xl={8}>
                <Form.Item label="生成时间" style={{ width: '100%', marginBottom: 12 }}>
                  <DatePicker.RangePicker showTime style={{ width: '100%' }} value={dateRange} onChange={(value) => setDateRange((value as [Dayjs, Dayjs]) || null)} />
                </Form.Item>
              </Col>
              <Col xs={24}>
                <Form.Item style={{ marginBottom: 0 }}>
                  <Space>
                    <Button type="primary" icon={<SearchOutlined />} onClick={handleSearch}>
                      搜索
                    </Button>
                    <Button icon={<ReloadOutlined />} onClick={handleReset}>
                      重置
                    </Button>
                  </Space>
                </Form.Item>
              </Col>
            </Row>
          </Form>
        </Card>
      )}

      <Card>
        <div className="table-toolbar">
          <Space wrap className="toolbar-buttons">
            <Button className="btn-plain-primary" icon={<PlusOutlined />} onClick={openGenerateDialog}>
              生成邀请码
            </Button>
            <Button className="btn-plain-warning" icon={<CloseCircleOutlined />} onClick={() => openCancelDialog()} disabled={selectedRows.length !== 1}>
              作废
            </Button>
            <Button className="btn-plain-danger" icon={<DeleteOutlined />} onClick={() => handleDelete()} disabled={selectedRows.length === 0}>
              删除
            </Button>
            <Button
              className="btn-plain-warning"
              icon={<DownloadOutlined />}
              onClick={() => download('/system/invite/export', addDateRange({ ...query }, formatRange(dateRange)), `invite_${Date.now()}.xlsx`)}
            >
              导出
            </Button>
          </Space>
          <div className="right-toolbar-wrap">
            <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQueryTable={() => loadList(query, dateRange)} />
          </div>
        </div>

        <Table<InviteCodeVO>
          rowKey="inviteId"
          loading={loading}
          bordered
          columns={columns}
          dataSource={list}
          pagination={false}
          rowSelection={{
            selectedRowKeys: selectedIds,
            onChange: (keys, rows) => {
              setSelectedIds(keys as Array<string | number>);
              setSelectedRows(rows);
            }
          }}
        />

        <Pagination
          total={total}
          page={query.pageNum}
          limit={query.pageSize}
          onPageChange={({ page, limit }) => {
            const next = { ...query, pageNum: page, pageSize: limit };
            setQuery(next);
            loadList(next, dateRange);
          }}
        />
      </Card>

      <Modal
        open={generateDialogOpen}
        title="生成邀请码"
        confirmLoading={submitting}
        onCancel={closeGenerateDialog}
        onOk={handleGenerateSubmit}
      >
        <Form form={generateForm} layout="vertical" initialValues={initialGenerateForm}>
          <Form.Item label="生成数量" name="generateCount" rules={[{ required: true, message: '生成数量不能为空' }]}>
            <InputNumber min={1} max={100} precision={0} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item label="永久有效" name="permanent" valuePropName="checked">
            <Switch />
          </Form.Item>
          {!generatePermanent && (
            <Form.Item
              label="过期时间"
              name="expireTime"
              rules={[{ required: true, message: '请选择过期时间' }]}
            >
              <DatePicker showTime style={{ width: '100%' }} format="YYYY-MM-DD HH:mm:ss" />
            </Form.Item>
          )}
          <Form.Item label="备注" name="remark">
            <Input.TextArea rows={4} maxLength={255} showCount placeholder="请输入用途备注" />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={cancelDialogOpen}
        title="作废邀请码"
        confirmLoading={submitting}
        onCancel={closeCancelDialog}
        onOk={handleCancelSubmit}
      >
        <Form form={cancelForm} layout="vertical" initialValues={initialCancelForm}>
          <Form.Item label="作废原因" name="canceledReason" rules={[{ required: true, message: '作废原因不能为空' }]}>
            <Input.TextArea rows={4} maxLength={255} showCount placeholder="请输入作废原因" />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  );
}

// infoq-scaffold-frontend-vue/src/views/system/invite/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="search">
        <el-form ref="queryFormRef" :model="queryParams" :inline="true" label-width="90px">
          <el-form-item label="邀请码" prop="inviteCode">
            <el-input v-model="queryParams.inviteCode" placeholder="请输入邀请码" clearable @keyup.enter="handleQuery" />
          </el-form-item>
          <el-form-item label="总状态" prop="status">
            <el-select v-model="queryParams.status" placeholder="请选择状态" clearable>
              <el-option v-for="dict in sys_invite_code_status" :key="dict.value" :label="dict.label" :value="dict.value" />
            </el-select>
          </el-form-item>
          <el-form-item label="使用人邮箱" prop="usedUserEmail">
            <el-input v-model="queryParams.usedUserEmail" placeholder="请输入使用人邮箱" clearable @keyup.enter="handleQuery" />
          </el-form-item>
          <el-form-item label="生成人" prop="creatorName">
            <el-input v-model="queryParams.creatorName" placeholder="请输入生成人" clearable @keyup.enter="handleQuery" />
          </el-form-item>
          <el-form-item label="生成时间" style="width: 360px">
            <el-date-picker
              v-model="dateRange"
              value-format="YYYY-MM-DD HH:mm:ss"
              type="daterange"
              range-separator="-"
              start-placeholder="开始时间"
              end-placeholder="结束时间"
              :default-time="[new Date(2000, 1, 1, 0, 0, 0), new Date(2000, 1, 1, 23, 59, 59)]"
            />
          </el-form-item>
          <el-form-item>
            <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
            <el-button icon="Refresh" @click="resetQuery">重置</el-button>
          </el-form-item>
        </el-form>
      </div>
    </transition>

    <el-card shadow="never">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:invite:add']" type="primary" plain icon="Plus" @click="handleOpenGenerate">生成邀请码</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:invite:edit']" type="warning" plain icon="CircleClose" :disabled="single" @click="handleOpenCancel()">
              作废
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:invite:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:invite:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
          </el-col>
          <right-toolbar v-model:show-search="showSearch" @query-table="getList" />
        </el-row>
      </template>

      <el-table v-loading="loading" :data="inviteList" border @selection-change="handleSelectionChange">
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column label="邀请码" min-width="250" align="center">
          <template #default="scope">
            <div class="invite-code-cell">
              <span class="invite-code-text">{{ scope.row.inviteCode }}</span>
              <el-button link type="primary" icon="DocumentCopy" @click="handleCopy(scope.row.inviteCode)">复制</el-button>
            </div>
          </template>
        </el-table-column>
        <el-table-column label="总状态" align="center" prop="status" width="120">
          <template #default="scope">
            <dict-tag :options="sys_invite_code_status" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="使用人邮箱" align="center" prop="usedUserEmail" min-width="180" :show-overflow-tooltip="true" />
        <el-table-column label="生成人" align="center" prop="creatorName" width="140" :show-overflow-tooltip="true" />
        <el-table-column label="生成时间" align="center" prop="createTime" width="180">
          <template #default="scope">
            <span>{{ proxy?.parseTime(scope.row.createTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="过期时间" align="center" prop="expireTime" width="180">
          <template #default="scope">
            <span>{{ proxy?.parseTime(scope.row.expireTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="使用时间" align="center" prop="usedTime" width="180">
          <template #default="scope">
            <span>{{ proxy?.parseTime(scope.row.usedTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="作废时间" align="center" prop="canceledTime" width="180">
          <template #default="scope">
            <span>{{ proxy?.parseTime(scope.row.canceledTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="备注" align="center" prop="remark" min-width="180" :show-overflow-tooltip="true" />
        <el-table-column label="作废原因" align="center" prop="canceledReason" min-width="180" :show-overflow-tooltip="true" />
        <el-table-column label="操作" align="center" width="180" class-name="small-padding fixed-width">
          <template #default="scope">
            <el-tooltip content="作废" placement="top">
              <el-button
                v-hasPermi="['system:invite:edit']"
                link
                type="primary"
                icon="CircleClose"
                :disabled="!canCancel(scope.row)"
                @click="handleOpenCancel(scope.row)"
              />
            </el-tooltip>
            <el-tooltip content="删除" placement="top">
              <el-button
                v-hasPermi="['system:invite:remove']"
                link
                type="primary"
                icon="Delete"
                :disabled="!canDelete(scope.row)"
                @click="handleDelete(scope.row)"
              />
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>

    <el-dialog v-model="generateDialog.visible" :title="generateDialog.title" width="520px" append-to-body>
      <el-form ref="generateFormRef" :model="generateForm" :rules="generateRules" label-width="100px">
        <el-form-item label="生成数量" prop="generateCount">
          <el-input-number v-model="generateForm.generateCount" :min="1" :max="100" :step="1" controls-position="right" />
        </el-form-item>
        <el-form-item label="永久有效">
          <el-switch v-model="generateForm.permanent" />
        </el-form-item>
        <el-form-item v-if="!generateForm.permanent" label="过期时间" prop="expireTime">
          <el-date-picker v-model="generateForm.expireTime" type="datetime" value-format="YYYY-MM-DD HH:mm:ss" placeholder="请选择过期时间" />
        </el-form-item>
        <el-form-item label="备注" prop="remark">
          <el-input v-model="generateForm.remark" type="textarea" :rows="4" maxlength="255" show-word-limit placeholder="请输入用途备注" />
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitGenerateForm">确定</el-button>
          <el-button @click="closeGenerateDialog">取消</el-button>
        </div>
      </template>
    </el-dialog>

    <el-dialog v-model="cancelDialog.visible" :title="cancelDialog.title" width="520px" append-to-body>
      <el-form ref="cancelFormRef" :model="cancelForm" :rules="cancelRules" label-width="100px">
        <el-form-item label="作废原因" prop="canceledReason">
          <el-input v-model="cancelForm.canceledReason" type="textarea" :rows="4" maxlength="255" show-word-limit placeholder="请输入作废原因" />
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitCancelForm">确定</el-button>
          <el-button @click="closeCancelDialog">取消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Invite" lang="ts">
import { cancelInvite, delInvite, generateInvite, listInvite } from '@/api/system/invite';
import type { InviteCodeCancelForm, InviteCodeGenerateForm, InviteCodeQuery, InviteCodeVO } from '@/api/system/invite/types';
import { toDictRefs } from '@/utils/dict';

interface InviteGenerateViewForm extends InviteCodeGenerateForm {
  permanent: boolean;
}

interface InviteCancelViewForm {
  inviteId?: number | string;
  canceledReason: string;
}

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_invite_code_status } = toDictRefs((proxy?.useDict('sys_invite_code_status') ?? {}) as Record<'sys_invite_code_status', DictDataOption[]>);

const inviteList = ref<InviteCodeVO[]>([]);
const selectedRows = ref<InviteCodeVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<string | number>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);
const dateRange = ref<[DateModelType, DateModelType]>(['', '']);

const queryFormRef = ref<ElFormInstance>();
const generateFormRef = ref<ElFormInstance>();
const cancelFormRef = ref<ElFormInstance>();

const generateDialog = reactive<DialogOption>({
  visible: false,
  title: '生成邀请码'
});

const cancelDialog = reactive<DialogOption>({
  visible: false,
  title: '作废邀请码'
});

const queryParams = reactive<InviteCodeQuery>({
  pageNum: 1,
  pageSize: 10,
  inviteCode: '',
  status: '',
  usedUserEmail: '',
  creatorName: ''
});

const initGenerateFormData: InviteGenerateViewForm = {
  generateCount: 1,
  expireTime: undefined,
  remark: '',
  permanent: true
};

const initCancelFormData: InviteCancelViewForm = {
  inviteId: undefined,
  canceledReason: ''
};

const generateForm = reactive<InviteGenerateViewForm>({ ...initGenerateFormData });
const cancelForm = reactive<InviteCancelViewForm>({ ...initCancelFormData });

const generateRules: ElFormRules<InviteGenerateViewForm> = {
  generateCount: [{ required: true, message: '生成数量不能为空', trigger: 'blur' }],
  expireTime: [
    {
      validator: (_rule, value, callback) => {
        if (!generateForm.permanent && !value) {
          callback(new Error('请选择过期时间'));
          return;
        }
        callback();
      },
      trigger: 'change'
    }
  ]
};

const cancelRules: ElFormRules<InviteCancelViewForm> = {
  canceledReason: [{ required: true, message: '作废原因不能为空', trigger: 'blur' }]
};

const canCancel = (row: InviteCodeVO) => row.status === '0';
const canDelete = (row: InviteCodeVO) => row.status !== '1';

const getList = async () => {
  loading.value = true;
  try {
    const res = await listInvite(proxy?.addDateRange({ ...queryParams }, dateRange.value));
    inviteList.value = res.rows;
    total.value = res.total;
  } finally {
    loading.value = false;
  }
};

const resetGenerateForm = () => {
  Object.assign(generateForm, initGenerateFormData);
  generateFormRef.value?.resetFields();
};

const resetCancelForm = () => {
  Object.assign(cancelForm, initCancelFormData);
  cancelFormRef.value?.resetFields();
};

const handleQuery = () => {
  queryParams.pageNum = 1;
  getList();
};

const resetQuery = () => {
  dateRange.value = ['', ''];
  queryFormRef.value?.resetFields();
  handleQuery();
};

const handleSelectionChange = (selection: InviteCodeVO[]) => {
  selectedRows.value = selection;
  ids.value = selection.map((item) => item.inviteId);
  single.value = selection.length !== 1;
  multiple.value = !selection.length;
};

const handleOpenGenerate = () => {
  resetGenerateForm();
  generateDialog.visible = true;
};

const closeGenerateDialog = () => {
  generateDialog.visible = false;
  resetGenerateForm();
};

const submitGenerateForm = () => {
  generateFormRef.value?.validate(async (valid: boolean) => {
    if (!valid) {
      return;
    }
    await generateInvite({
      generateCount: generateForm.generateCount,
      expireTime: generateForm.permanent ? undefined : generateForm.expireTime,
      remark: generateForm.remark
    });
    proxy?.$modal.msgSuccess('生成成功');
    closeGenerateDialog();
    await getList();
  });
};

const resolveCancelRow = (row?: InviteCodeVO) => {
  const target = row ?? selectedRows.value[0];
  if (!target) {
    proxy?.$modal.msgWarning('请选择需要作废的邀请码');
    return undefined;
  }
  if (!canCancel(target)) {
    proxy?.$modal.msgWarning('仅未使用的邀请码允许作废');
    return undefined;
  }
  return target;
};

const handleOpenCancel = (row?: InviteCodeVO) => {
  const target = resolveCancelRow(row);
  if (!target) {
    return;
  }
  resetCancelForm();
  cancelForm.inviteId = target.inviteId;
  cancelDialog.visible = true;
};

const closeCancelDialog = () => {
  cancelDialog.visible = false;
  resetCancelForm();
};

const submitCancelForm = () => {
  cancelFormRef.value?.validate(async (valid: boolean) => {
    if (!valid || cancelForm.inviteId == null) {
      return;
    }
    await cancelInvite({
      inviteId: cancelForm.inviteId,
      canceledReason: cancelForm.canceledReason
    } as InviteCodeCancelForm);
    proxy?.$modal.msgSuccess('作废成功');
    closeCancelDialog();
    await getList();
  });
};

const handleDelete = async (row?: InviteCodeVO) => {
  const targetRows = row ? [row] : selectedRows.value;
  if (!targetRows.length) {
    proxy?.$modal.msgWarning('请选择需要删除的邀请码');
    return;
  }
  if (targetRows.some((item) => !canDelete(item))) {
    proxy?.$modal.msgWarning('已使用的邀请码不允许删除');
    return;
  }
  const targetIds = row ? row.inviteId : ids.value;
  const codeText = targetRows.map((item) => item.inviteCode).join('、');
  await proxy?.$modal.confirm('是否确认删除邀请码 "' + codeText + '" ?');
  await delInvite(targetIds);
  proxy?.$modal.msgSuccess('删除成功');
  await getList();
};

const handleExport = () => {
  proxy?.download('system/invite/export', proxy?.addDateRange({ ...queryParams }, dateRange.value), `invite_${new Date().getTime()}.xlsx`);
};

const handleCopy = async (inviteCode: string) => {
  const textArea = document.createElement('textarea');
  textArea.value = inviteCode;
  textArea.style.position = 'fixed';
  textArea.style.left = '-9999px';
  document.body.appendChild(textArea);
  textArea.select();
  document.execCommand('copy');
  document.body.removeChild(textArea);
  proxy?.$modal.msgSuccess('邀请码已复制');
};

onMounted(() => {
  getList();
});
</script>

<style lang="scss" scoped>
.invite-code-cell {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}

.invite-code-text {
  font-family: Consolas, Monaco, monospace;
  word-break: break-all;
}
</style>
