// infoq-scaffold-frontend-weapp-vue/src/pages/home/index.vue
<template>
  <view class="home-container">
    <view class="welcome-section">
      <view class="avatar-wrapper">
        <image :src="avatarImage" class="avatar-img" mode="aspectFill" @error="handleAvatarLoadError" />
      </view>
      <view class="welcome-text">
        <view class="greet">您好，{{ displayName }}</view>
        <view class="dept">{{ sessionStore.user?.deptName || 'AI-first 全栈脚手架' }}</view>
      </view>
    </view>

    <swiper
      circular
      autoplay
      indicator-dots
      indicator-active-color="#1677ff"
      indicator-color="rgba(22, 119, 255, 0.2)"
      class="stats-swiper"
      :interval="4000"
      :duration="360"
    >
      <swiper-item class="stats-item">
        <view class="stats-card">
          <view class="stats-label">
            <AppIcon name="user" size="32" color="inherit" class="stats-icon-modern" />
            用户总数
          </view>
          <view class="stats-value">{{ summary.userTotal }}</view>
        </view>
      </swiper-item>
      <swiper-item class="stats-item">
        <view class="stats-card">
          <view class="stats-label">
            <AppIcon name="bookmark" size="32" color="inherit" class="stats-icon-modern" />
            角色总数
          </view>
          <view class="stats-value">{{ summary.roleTotal }}</view>
        </view>
      </swiper-item>
      <swiper-item class="stats-item">
        <view class="stats-card">
          <view class="stats-label">
            <AppIcon name="eye" size="32" color="inherit" class="stats-icon-modern" />
            在线设备
          </view>
          <view class="stats-value">{{ summary.onlineTotal }}</view>
        </view>
      </swiper-item>
    </swiper>

    <view class="notice-section" @click="openNotices">
      <view class="notice-bar">
        <AppIcon name="volume" size="36" color="#1677ff" class="notice-icon-modern" />
        <view class="notice-content">
          <view class="notice-scroll">
            {{ primaryNotice ? `${primaryNotice.noticeTitle} · ${primaryNotice.createTime}` : '暂无最新系统公告' }}
          </view>
        </view>
        <view class="notice-extra">详情</view>
      </view>
    </view>

    <view class="card-container grid-section">
      <view class="card-header">
        <text class="card-title">快捷入口</text>
        <text class="card-extra">管理台核心模块</text>
      </view>
      <view class="card-content">
        <view class="quick-grid">
          <view
            class="quick-item"
            v-for="item in gridItems"
            :key="item.key"
            @click="handleGridClick(item)"
          >
            <view class="icon-box" :class="{ disabled: item.disabled }">
              <AppIcon :name="item.key" size="56" color="#1677ff" />
            </view>
            <text class="label" :class="{ disabled: item.disabled }">{{ item.title }}</text>
          </view>
        </view>
      </view>
    </view>

    <BottomNav active="home" />
  </view>
</template>

<script setup lang="ts">
import {computed, ref, watch} from 'vue';
import {onShow} from '@dcloudio/uni-app';
import BottomNav from '@/components/BottomNav.vue';
import AppIcon from '@/components/AppIcon.vue';
import defaultAvatar from '@/assets/images/profile.jpg';
import {adminModules} from '@/utils/admin';
import {resolveAvatarUrl} from '@/utils/avatar';
import {navigate, routes} from '@/utils/navigation';
import {handlePageError} from '@/utils/ui';
import {ensureAuthenticated} from '@/composables/use-auth-guard';
import {listNotice, loadWorkbenchSummary, type NoticeVO} from '@/api';
import {useSessionStore} from '@/store/session';

const sessionStore = useSessionStore();
const recentNotices = ref<NoticeVO[]>([]);
const summary = ref({
  userTotal: 0,
  roleTotal: 0,
  onlineTotal: 0,
  loginTotal: 0
});

const displayName = computed(() => (sessionStore.user?.nickName || sessionStore.user?.userName || '用户'));
const avatarLoadFailed = ref(false);
watch(
  () => sessionStore.user?.avatar,
  () => {
    avatarLoadFailed.value = false;
  }
);

const avatarImage = computed(() => {
  if (avatarLoadFailed.value) {
    return defaultAvatar;
  }
  return resolveAvatarUrl(sessionStore.user?.avatar) || defaultAvatar;
});

const handleAvatarLoadError = () => {
  avatarLoadFailed.value = true;
};

const primaryNotice = computed(() => recentNotices.value[0]);
type GridItem = (typeof adminModules)[number] & { disabled: boolean };
const isGridItem = (item: GridItem | null): item is GridItem => item !== null;

const gridItems = computed<GridItem[]>(() => {
  const keys = ['users', 'roles', 'depts', 'notices', 'online', 'loginInfo'] as const;
  return keys.map((key) => {
    const mod = adminModules.find((item) => item.key === key);
    if (!mod) return null;
    return {
      ...mod,
      disabled: !sessionStore.permissions.includes(mod.permission)
    };
  }).filter(isGridItem);
});

const openNotices = () => {
  if (!sessionStore.permissions.includes('system:notice:list')) return;
  navigate(routes.notices);
};

const handleGridClick = async (item: GridItem) => {
  if (item.disabled) {
    await uni.showToast({ title: '暂无权限访问', icon: 'none' });
    return;
  }
  navigate(item.url);
};

const loadPage = async () => {
  if (!ensureAuthenticated()) return;
  try {
    const session = await sessionStore.loadSession();
    if (!session) {
      uni.reLaunch({ url: routes.login });
      return;
    }
    summary.value = await loadWorkbenchSummary(sessionStore.permissions);
    if (sessionStore.permissions.includes('system:notice:list')) {
      const response = await listNotice({
        pageNum: 1, pageSize: 3, noticeTitle: '', createByName: '', status: '0', noticeType: ''
      });
      recentNotices.value = response.rows;
    }
  } catch (error) {
    await handlePageError(error, '首页加载失败');
  }
};

onShow(() => {
  void loadPage();
});
</script>

<style lang="scss">
@import './index.scss';

.stats-icon-modern {
  margin-right: 12rpx;
  opacity: 0.8;
}

.notice-icon-modern {
  margin-right: 16rpx;
  flex-shrink: 0;
}
</style>

// infoq-scaffold-frontend-weapp-react/src/pages/home/index.tsx
import {Swiper, SwiperItem, Text, View} from '@tarojs/components';
import Taro, {useDidShow} from '@tarojs/taro';
import {AtAvatar, AtGrid, AtIcon, AtNoticebar} from 'taro-ui';
import {type AdminModuleKey, formatDateTime, listNotice, loadWorkbenchSummary, type NoticeVO} from '@/api';
import defaultAvatar from '@/assets/images/profile.jpg';
import {useState} from 'react';
import BottomNav from '../../components/bottom-nav';
import {adminModules} from '../../utils/admin';
import {resolveAvatarUrl} from '../../utils/avatar';
import {navigate, routes} from '../../utils/navigation';
import {handlePageError} from '../../utils/ui';
import {useSessionStore} from '../../store/session';
import './index.scss';

const gridModuleKeys: AdminModuleKey[] = ['users', 'roles', 'depts', 'notices', 'online', 'loginInfo'];

const gridIconMap: Record<AdminModuleKey, string> = {
  users: 'user',
  roles: 'bookmark',
  depts: 'folder',
  dicts: 'equalizer',
  posts: 'calendar',
  menus: 'menu',
  notices: 'message',
  online: 'eye',
  loginInfo: 'file-generic',
  operLog: 'list',
  cache: 'settings'
};

type HomeGridItem = {
  disabled: boolean;
  key: AdminModuleKey;
  permission: string;
  url: string;
  value: string;
  iconInfo: {
    color: string;
    size: number;
    value: string;
  };
};

const noticeQuery = {
  pageNum: 1,
  pageSize: 3,
  noticeTitle: '',
  createByName: '',
  status: '',
  noticeType: ''
};

export default function HomePage() {
  const user = useSessionStore((state) => state.user);
  const permissions = useSessionStore((state) => state.permissions);
  const loadSession = useSessionStore((state) => state.loadSession);
  const [recentNotices, setRecentNotices] = useState<NoticeVO[]>([]);
  const [summary, setSummary] = useState({
    userTotal: 0,
    roleTotal: 0,
    onlineTotal: 0,
    loginTotal: 0
  });

  useDidShow(() => {
    const run = async () => {
      try {
        const session = await loadSession();
        if (!session) {
          Taro.reLaunch({ url: routes.login });
          return;
        }
        const currentPermissions = useSessionStore.getState().permissions;
        const nextSummary = await loadWorkbenchSummary(currentPermissions);
        setSummary(nextSummary);
        if (currentPermissions.includes('system:notice:list')) {
          const response = await listNotice(noticeQuery);
          setRecentNotices(response.rows);
        } else {
          setRecentNotices([]);
        }
      } catch (error) {
        await handlePageError(error, '首页加载失败');
      }
    };
    void run();
  });

  const canOpenNotice = permissions.includes('system:notice:list');
  const primaryNotice = recentNotices[0];
  const avatarImage = resolveAvatarUrl(user?.avatar) || defaultAvatar;
  const gridItems: HomeGridItem[] = gridModuleKeys.map((key) => {
    const module = adminModules.find((item) => item.key === key);
    if (!module) {
      throw new Error(`Missing admin module metadata for ${key}.`);
    }
    const enabled = permissions.includes(module.permission);
    return {
      key,
      permission: module.permission,
      url: module.url,
      value: module.title,
      disabled: !enabled,
      iconInfo: {
        value: gridIconMap[key],
        size: 28,
        color: enabled ? '#1677ff' : '#c0c4cc'
      }
    };
  });

  const handleGridClick = async (item: HomeGridItem) => {
    if (item.disabled) {
      await Taro.showToast({
        title: '当前账号没有访问该模块的权限',
        icon: 'none'
      });
      return;
    }
    navigate(item.url);
  };

  const displayName = (user?.nickName || user?.userName || '用户').slice(0, 1).toUpperCase();

  return (
    <View className="home-container">
      <View className="welcome-section">
        <AtAvatar circle size="large" image={avatarImage} text={displayName} />
        <View className="welcome-text">
          <View className="greet">您好，{user?.nickName || user?.userName || '用户'}</View>
          <View className="dept">{user?.deptName || 'AI-first 全栈脚手架'}</View>
        </View>
      </View>

      <Swiper
        circular
        className="stats-swiper"
        duration={360}
        indicatorActiveColor="#1677ff"
        indicatorColor="rgba(22, 119, 255, 0.2)"
        indicatorDots
        interval={4000}
        autoplay
      >
        <SwiperItem className="stats-item">
          <View className="stats-card">
            <View className="stats-label">
              <AtIcon value="user" size="20" className="stats-icon" />
              用户总数
            </View>
            <View className="stats-value">{summary.userTotal}</View>
          </View>
        </SwiperItem>
        <SwiperItem className="stats-item">
          <View className="stats-card">
            <View className="stats-label">
              <AtIcon value="bookmark" size="20" className="stats-icon" />
              角色总数
            </View>
            <View className="stats-value">{summary.roleTotal}</View>
          </View>
        </SwiperItem>
        <SwiperItem className="stats-item">
          <View className="stats-card">
            <View className="stats-label">
              <AtIcon value="eye" size="20" className="stats-icon" />
              在线设备
            </View>
            <View className="stats-value">{summary.onlineTotal}</View>
          </View>
        </SwiperItem>
      </Swiper>

      <View className="notice-section">
        <AtNoticebar
          icon="volume-plus"
          marquee
          moreText={primaryNotice ? '详情' : '全部'}
          showMore={canOpenNotice}
          single
          onGotoMore={() => {
            if (!canOpenNotice) return;
            if (primaryNotice) {
              navigate(`${routes.noticeDetail}?noticeId=${primaryNotice.noticeId}`);
            } else {
              navigate(routes.notices);
            }
          }}
        >
          {!canOpenNotice
            ? '当前账号没有公告查看权限'
            : primaryNotice
              ? `${primaryNotice.noticeTitle} · ${formatDateTime(primaryNotice.createTime)}`
              : '暂无公告数据'}
        </AtNoticebar>
      </View>

      <View className="card-container grid-section">
        <View className="card-header">
          <Text className="card-title">快捷入口</Text>
          <Text className="card-extra">管理台核心模块</Text>
        </View>
        <View className="card-content">
          <AtGrid
            data={gridItems}
            columnNum={3}
            hasBorder={false}
            onClick={(item) => void handleGridClick(item as HomeGridItem)}
          />
        </View>
      </View>

      <BottomNav active="home" />
    </View>
  );
}
