// infoq-scaffold-frontend-weapp-react/src/pages/system-menus/form/index.tsx
import {Picker, Text, View} from '@tarojs/components';
import Taro, {useDidShow, useRouter} from '@tarojs/taro';
import {
  addMenu,
  assertArrayData,
  type DeptTreeVO,
  type DictOption,
  flattenTree,
  type FlatTreeItem,
  getDicts,
  getMenu,
  type MenuForm,
  menuTreeSelect,
  type MenuType,
  toDictOptions,
  updateMenu
} from '@/api';
import {useState} from 'react';
import {AtButton, AtInput, AtTextarea} from 'taro-ui';
import {handlePageError, showSuccess} from '../../../utils/ui';
import {useSessionStore} from '../../../store/session';
import {routes} from '../../../utils/navigation';
import './index.scss';

const menuTypeOptions = [
  { label: '目录', value: 'M' as const },
  { label: '菜单', value: 'C' as const },
  { label: '按钮', value: 'F' as const }
];

const visibleOptions = [
  { label: '显示', value: '0' },
  { label: '隐藏', value: '1' }
];

const createForm = (): MenuForm => ({
  parentId: 0,
  menuId: undefined,
  menuName: '',
  orderNum: 1,
  path: '',
  component: '',
  menuType: 'M',
  visible: '0',
  status: '0',
  perms: '',
  icon: '',
  remark: ''
});

export default function MenuFormPage() {
  const router = useRouter();
  const menuId = router.params.menuId;
  const parentIdFromUrl = router.params.parentId;
  const loadSession = useSessionStore((state) => state.loadSession);
  const [form, setForm] = useState<MenuForm>(createForm());
  const [statusOptions, setStatusOptions] = useState<DictOption[]>([]);
  const [treeOptions, setTreeOptions] = useState<Array<FlatTreeItem<DeptTreeVO>>>([]);
  const [submitting, setSubmitting] = useState(false);

  const loadData = async () => {
    try {
      const session = await loadSession();
      if (!session) {
        Taro.reLaunch({ url: routes.login });
        return;
      }

      const [statusRes, treeRes] = await Promise.all([
        getDicts('sys_normal_disable'),
        menuTreeSelect()
      ]);
      setStatusOptions(toDictOptions(statusRes.data));
      setTreeOptions(flattenTree(assertArrayData(treeRes.data, '菜单树响应 data')));

      if (menuId) {
        const response = await getMenu(menuId);
        const data = response.data;
        setForm({
          parentId: data.parentId,
          menuId: data.menuId,
          menuName: data.menuName,
          orderNum: data.orderNum,
          path: data.path || '',
          component: data.component || '',
          menuType: data.menuType,
          visible: data.visible || '0',
          status: data.status || '0',
          perms: data.perms || '',
          icon: data.icon || '',
          remark: data.remark || ''
        });
      } else if (parentIdFromUrl) {
        setForm(prev => ({ ...prev, parentId: Number(parentIdFromUrl) }));
      }
    } catch (error) {
      await handlePageError(error, '加载失败');
    }
  };

  useDidShow(() => {
    void loadData();
  });

  const handleSave = async () => {
    if (!form.menuName.trim()) {
      await Taro.showToast({ title: '请输入菜单名称', icon: 'none' });
      return;
    }

    setSubmitting(true);
    try {
      if (menuId) {
        await updateMenu(form);
      } else {
        await addMenu(form);
      }
      await showSuccess(menuId ? '菜单已更新' : '菜单已创建');
      Taro.navigateBack();
    } catch (error) {
      await handlePageError(error, '保存失败');
    } finally {
      setSubmitting(false);
    }
  };

  const parentMenuOptions = [
    { label: '顶级菜单', id: 0, _depth: 0 },
    ...treeOptions.filter(m => String(m.id) !== String(menuId))
  ];

  const selectedParent = parentMenuOptions.find(m => String(m.id) === String(form.parentId));
  const selectedParentLabel = selectedParent ? `${'· '.repeat(selectedParent._depth)}${selectedParent.label}` : '请选择上级菜单';

  const selectedType = menuTypeOptions.find(t => t.value === form.menuType);

  return (
    <View className="menu-form-container">
      <View className="form-section">
        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">基本信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            <Picker
              mode="selector"
              range={parentMenuOptions.map(m => `${'· '.repeat(m._depth)}${m.label}`)}
              onChange={(e) => {
                const index = Number(e.detail.value);
                setForm(prev => ({ ...prev, parentId: parentMenuOptions[index].id }));
              }}
            >
              <View className="at-input picker-input-aligned">
                <View className="at-input__container">
                  <View className="at-input__title">上级菜单</View>
                  <View className="at-input__input picker-value-container">
                    <Text className={`picker-value ${!selectedParent ? 'placeholder' : ''}`}>
                      {selectedParentLabel}
                    </Text>
                    <View className="at-icon at-icon-chevron-right picker-arrow"></View>
                  </View>
                </View>
              </View>
            </Picker>

            <Picker
              mode="selector"
              range={menuTypeOptions.map(t => t.label)}
              onChange={(e) => {
                const index = Number(e.detail.value);
                setForm(prev => ({ ...prev, menuType: menuTypeOptions[index].value as MenuType }));
              }}
            >
              <View className="at-input picker-input-aligned">
                <View className="at-input__container">
                  <View className="at-input__title">菜单类型</View>
                  <View className="at-input__input picker-value-container">
                    <Text className="picker-value">
                      {selectedType?.label || '选择类型'}
                    </Text>
                    <View className="at-icon at-icon-chevron-right picker-arrow"></View>
                  </View>
                </View>
              </View>
            </Picker>

            <AtInput
              name="menuName"
              title="菜单名称"
              placeholder="请输入菜单名称"
              value={form.menuName}
              onChange={(v) => { setForm(p => ({ ...p, menuName: String(v) })); return v; }}
            />
            <AtInput
              name="orderNum"
              title="显示顺序"
              type="number"
              placeholder="请输入显示顺序"
              value={String(form.orderNum || 1)}
              onChange={(v) => { setForm(p => ({ ...p, orderNum: Number(v || 1) })); return v; }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">配置信息</Text>
          </View>
          <View className="card-content" style={{ padding: 0 }}>
            {form.menuType !== 'F' && (
              <AtInput
                name="path"
                title="路由地址"
                placeholder="请输入路由地址"
                value={form.path || ''}
                onChange={(v) => { setForm(p => ({ ...p, path: String(v) })); return v; }}
              />
            )}
            <AtInput
              name="perms"
              title="权限标识"
              placeholder="请输入权限标识"
              value={form.perms || ''}
              onChange={(v) => { setForm(p => ({ ...p, perms: String(v) })); return v; }}
            />
            <AtInput
              name="icon"
              title="菜单图标"
              placeholder="请输入图标名称"
              value={form.icon || ''}
              onChange={(v) => { setForm(p => ({ ...p, icon: String(v) })); return v; }}
            />
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">状态控制</Text>
          </View>
          <View className="card-content">
            <View className="form-item-vertical">
              <Text className="item-label">显示状态</Text>
              <View className="radio-options-horizontal">
                {visibleOptions.map((item) => (
                  <View
                    key={item.value}
                    className={`radio-option-item ${form.visible === item.value ? 'active' : ''}`}
                    onClick={() => setForm((prev) => ({ ...prev, visible: item.value }))}
                  >
                    <View className="radio-circle">
                      {form.visible === item.value && <View className="radio-inner" />}
                    </View>
                    <Text className="radio-label">{item.label}</Text>
                  </View>
                ))}
              </View>
            </View>

            <View className="form-item-vertical" style={{ marginTop: '32rpx' }}>
              <Text className="item-label">菜单状态</Text>
              <View className="radio-options-horizontal">
                {statusOptions.map((item) => (
                  <View
                    key={item.value}
                    className={`radio-option-item ${form.status === item.value ? 'active' : ''}`}
                    onClick={() => setForm((prev) => ({ ...prev, status: item.value }))}
                  >
                    <View className="radio-circle">
                      {form.status === item.value && <View className="radio-inner" />}
                    </View>
                    <Text className="radio-label">{item.label}</Text>
                  </View>
                ))}
              </View>
            </View>
          </View>
        </View>

        <View className="card-container">
          <View className="card-header">
            <Text className="card-title">备注</Text>
          </View>
          <View className="card-content">
            <AtTextarea
              height={150}
              count={false}
              placeholder="请输入备注说明"
              value={form.remark || ''}
              onChange={(value) => setForm((prev) => ({ ...prev, remark: value }))}
            />
          </View>
        </View>
      </View>

      <View className="action-section">
        <AtButton className="save-btn" type="primary" loading={submitting} onClick={() => void handleSave()}>
          保存菜单
        </AtButton>
        <AtButton className="cancel-btn" onClick={() => Taro.navigateBack()}>
          返回
        </AtButton>
      </View>
    </View>
  );
}

// infoq-scaffold-frontend-weapp-vue/src/pages/system-users/form/index.vue
<template>
  <view class="page-wrap">
    <view class="form-section">
      <!-- 基本信息 -->
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">基本信息</text>
        </view>
        <view class="card-content" style="padding: 0">
          <picker
            mode="selector"
            :range="deptOptions.map(d => `${'· '.repeat(d._depth)}${d.label}`)"
            @change="handleDeptChange"
          >
            <view class="picker-input-aligned">
              <text class="picker-label">所属部门</text>
              <view class="picker-value-container">
                <text :class="['picker-value', !selectedDept ? 'placeholder' : '']">
                  {{ selectedDeptLabel }}
                </text>
                <AppIcon name="chevron-right" size="32" class="picker-arrow" />
              </view>
            </view>
          </picker>

          <view class="form-item-modern">
            <text class="form-label">登录账号</text>
            <input class="form-input-plain" v-model="form.userName" placeholder="请输入登录账号" :disabled="isEdit" placeholder-style="color: #94a3b8" />
          </view>

          <view class="form-item-modern">
            <text class="form-label">用户昵称</text>
            <input class="form-input-plain" v-model="form.nickName" placeholder="请输入用户昵称" placeholder-style="color: #94a3b8" />
          </view>

          <view class="form-item-modern" v-if="!isEdit">
            <text class="form-label">初始密码</text>
            <input class="form-input-plain" type="password" v-model="form.password" placeholder="请输入初始密码" placeholder-style="color: #94a3b8" />
          </view>

          <view class="form-item-modern">
            <text class="form-label">手机号码</text>
            <input class="form-input-plain" v-model="form.phonenumber" placeholder="请输入手机号码" placeholder-style="color: #94a3b8" />
          </view>
        </view>
      </view>

      <!-- 用户属性 -->
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">用户属性</text>
        </view>
        <view class="card-content">
          <view class="form-item-vertical">
            <text class="item-label">性别</text>
            <view class="radio-options-horizontal">
              <view
                v-for="item in sexOptions"
                :key="item.value"
                :class="['radio-option-item', form.sex === item.value ? 'active' : '']"
                @click="form.sex = item.value"
              >
                <view class="radio-circle">
                  <view v-if="form.sex === item.value" class="radio-inner" />
                </view>
                <text class="radio-label">{{ item.label }}</text>
              </view>
            </view>
          </view>

          <view class="form-item-vertical" style="margin-top: 32rpx">
            <text class="item-label">状态</text>
            <view class="radio-options-horizontal">
              <view
                v-for="item in statusOptions"
                :key="item.value"
                :class="['radio-option-item', form.status === item.value ? 'active' : '']"
                @click="form.status = item.value"
              >
                <view class="radio-circle">
                  <view v-if="form.status === item.value" class="radio-inner" />
                </view>
                <text class="radio-label">{{ item.label }}</text>
              </view>
            </view>
          </view>
        </view>
      </view>

      <!-- 分配角色 -->
      <view class="card-container">
        <view class="card-header">
          <text class="card-title">分配角色</text>
        </view>
        <view class="card-content">
          <view class="checkbox-group-vertical">
            <view
              v-for="item in roleOptions"
              :key="String(item.roleId)"
              :class="['checkbox-item', isRoleSelected(item.roleId) ? 'active' : '']"
              @click="toggleRole(item.roleId)"
            >
              <view :class="['checkbox-box', isRoleSelected(item.roleId) ? 'checked' : '']">
                <view v-if="isRoleSelected(item.roleId)" class="checkbox-inner" />
              </view>
              <text class="checkbox-label">{{ item.roleName }}</text>
            </view>
          </view>
        </view>
      </view>
    </view>

    <!-- 操作按钮 -->
    <view class="action-section">
      <button class="primary-btn save-btn" :loading="submitting" @click="save">保 存</button>
      <button class="secondary-btn cancel-btn" @click="backOr(routes.users)">取 消</button>
    </view>
  </view>
</template>

<script setup lang="ts">
import {computed, reactive, ref} from 'vue';
import {onLoad} from '@dcloudio/uni-app';
import AppIcon from '@/components/AppIcon.vue';
import {
  addUser,
  assertArrayData,
  deptTreeSelectForUser,
  type DeptTreeVO,
  type DictOption,
  flattenTree,
  type FlatTreeItem,
  getDicts,
  getUser,
  optionSelectRoles,
  type RoleVO,
  toDictOptions,
  updateUser,
  type UserForm
} from '@/api';
import {ensureAuthenticated, ensurePermission} from '@/composables/use-auth-guard';
import {backOr, routes} from '@/utils/navigation';
import {handlePageError, showSuccess} from '@/utils/ui';
import {useSessionStore} from '@/store/session';

const sessionStore = useSessionStore();
const userId = ref('');
const submitting = ref(false);
const statusOptions = ref<DictOption[]>([]);
const sexOptions = ref<DictOption[]>([]);
const deptOptions = ref<Array<FlatTreeItem<DeptTreeVO>>>([]);
const roleOptions = ref<RoleVO[]>([]);

const form = reactive<UserForm>({
  userName: '',
  password: '',
  nickName: '',
  phonenumber: '',
  email: '',
  sex: '0',
  status: '0',
  remark: '',
  deptId: undefined,
  roleIds: [],
  postIds: []
});

const isEdit = computed(() => Boolean(userId.value));
type PickerChangeEvent = { detail?: { value?: string | number } };

const selectedDept = computed(() => deptOptions.value.find(d => Number(d.id) === form.deptId));
const selectedDeptLabel = computed(() => selectedDept.value ? `${'· '.repeat(selectedDept.value._depth)}${selectedDept.value.label}` : '请选择部门');

const handleDeptChange = (event: PickerChangeEvent) => {
  const index = Number(event.detail?.value);
  const target = Number.isInteger(index) ? deptOptions.value[index] : undefined;
  if (!target) {
    return;
  }
  form.deptId = Number(target.id);
};

const isRoleSelected = (roleId: string | number) => (form.roleIds || []).includes(String(roleId));
const toggleRole = (roleId: string | number) => {
  const idStr = String(roleId);
  const current = form.roleIds || [];
  if (current.includes(idStr)) {
    form.roleIds = current.filter(id => id !== idStr);
  } else {
    form.roleIds = [...current, idStr];
  }
};

const loadData = async () => {
  try {
    const [statusRes, sexRes, deptRes, roleRes] = await Promise.all([
      getDicts('sys_normal_disable'),
      getDicts('sys_user_sex'),
      deptTreeSelectForUser(),
      optionSelectRoles()
    ]);

    statusOptions.value = toDictOptions(statusRes.data);
    sexOptions.value = toDictOptions(sexRes.data);
    deptOptions.value = flattenTree(deptRes.data);
    roleOptions.value = assertArrayData(roleRes.data, '角色选项响应 data');

    if (userId.value) {
      const response = await getUser(userId.value);
      const { user, roleIds, postIds } = response.data;
      Object.assign(form, {
        ...user,
        userId: String(user.userId),
        roleIds: assertArrayData<string | number>(roleIds, '用户详情响应 data.roleIds').map(String),
        postIds: assertArrayData<string | number>(postIds, '用户详情响应 data.postIds').map(String)
      });
    }
  } catch (error) {
    await handlePageError(error, '数据加载失败');
  }
};

const save = async () => {
  if (!form.deptId) {
    await uni.showToast({ title: '请选择所属部门', icon: 'none' });
    return;
  }
  if (!form.userName?.trim()) {
    await uni.showToast({ title: '请输入登录账号', icon: 'none' });
    return;
  }
  if (!form.nickName?.trim()) {
    await uni.showToast({ title: '请输入用户昵称', icon: 'none' });
    return;
  }
  if (!isEdit.value && !form.password?.trim()) {
    await uni.showToast({ title: '请输入初始密码', icon: 'none' });
    return;
  }

  submitting.value = true;
  try {
    if (!ensureAuthenticated()) return;
    await sessionStore.loadSession();
    if (isEdit.value) {
      await updateUser(form);
    } else {
      await addUser(form);
    }
    await showSuccess('保存成功');
    backOr(routes.users);
  } catch (error) {
    await handlePageError(error, '保存失败');
  } finally {
    submitting.value = false;
  }
};

onLoad((query) => {
  const initPage = async () => {
    if (!ensureAuthenticated()) return;

    userId.value = String(query?.userId || '').trim();
    if (userId.value) {
      try {
        const allowed = await ensurePermission('system:user:query', {
          fallbackRoute: routes.users,
          failureMessage: '当前账号没有用户查询权限'
        });
        if (!allowed) {
          return;
        }
      } catch (error) {
        await handlePageError(error, '数据加载失败');
        return;
      }
    }

    await loadData();
  };

  void initPage();
});
</script>

<style lang="scss">
@import '@/styles/common.scss';
</style>
